// --------------- //
//    Tool types   //
// --------------- //



/**
 * Type of ABLY's ABLY_BATCH_PRESENCE tool input.
 */
type ABLY_BATCH_PRESENCE_INPUT = {
  /**
   * Channels
   * @description Comma-separated list of channel names to query presence for
   */
  channels?: string;
  /**
   * Separator
   * @description Character used to separate channel names (default is comma)
   * @default ,
   */
  separator: string;
};

/**
 * Type of ABLY's ABLY_BATCH_PRESENCE tool output.
 */
type ABLY_BATCH_PRESENCE_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Items
       * @description List of presence data for each requested channel
       */
      items: {
          /**
           * Channel
           * @description The name of the channel
           */
          channel: string;
          /**
           * Presence
           * @description List of presence members in the channel
           */
          presence: {
              /**
               * Action
               * @description The presence action (1=enter, 2=leave, 3=update)
               */
              action: number;
              /**
               * Client Id
               * @description The client identifier
               */
              client_id: string;
              /**
               * Connection Id
               * @description The connection identifier
               */
              connection_id: string;
              /**
               * Data
               * @description Optional data associated with the presence member
               * @default null
               */
              data: {
                  [key: string]: unknown;
              } | null;
              /**
               * Timestamp
               * @description The timestamp of the presence update
               */
              timestamp: number;
          }[];
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_BATCH_PRESENCE_HISTORY tool input.
 */
type ABLY_BATCH_PRESENCE_HISTORY_INPUT = {
  /**
   * Channels
   * @description List of channel names to query presence history for
   */
  channels?: string[];
  /**
   * Direction
   * @description Direction of results (backwards or forwards)
   * @default backwards
   */
  direction: string | null;
  /**
   * End
   * @description End time in milliseconds since epoch
   * @default null
   */
  end: number | null;
  /**
   * Limit
   * @description Maximum number of messages to return per channel (default 100, max 1000)
   * @default 100
   */
  limit: number | null;
  /**
   * Start
   * @description Start time in milliseconds since epoch
   * @default null
   */
  start: number | null;
};

/**
 * Type of ABLY's ABLY_BATCH_PRESENCE_HISTORY tool output.
 */
type ABLY_BATCH_PRESENCE_HISTORY_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Items
       * @description List of presence history data for each requested channel
       */
      items: {
          /**
           * Channel
           * @description The name of the channel
           */
          channel: string;
          /**
           * Presence
           * @description List of presence history messages for the channel
           */
          presence: {
              /**
               * Action
               * @description The presence action (1=enter, 2=leave, 3=update)
               */
              action: number;
              /**
               * Client Id
               * @description The client identifier that published the message
               * @default null
               */
              client_id: string | null;
              /**
               * Connection Id
               * @description The connection identifier
               */
              connection_id: string;
              /**
               * Data
               * @description Optional data associated with the presence message
               * @default null
               */
              data: unknown;
              /**
               * Id
               * @description A unique message identifier generated by Ably
               */
              id: string;
              /**
               * Timestamp
               * @description The timestamp of the presence update in milliseconds since epoch
               */
              timestamp: number;
          }[];
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_CREATE_CHANNEL tool input.
 */
type ABLY_CREATE_CHANNEL_INPUT = {
  /**
   * Channel Id
   * @description The name of the channel to create/initialize. Must be less than 1024 characters and can contain alphanumeric characters, hyphen, underscore, colon, and period.
   */
  channel_id?: string;
};

/**
 * Type of ABLY's ABLY_CREATE_CHANNEL tool output.
 */
type ABLY_CREATE_CHANNEL_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Channel Id
       * @description The name of the channel that was created/initialized
       */
      channel_id: string;
      /**
       * Status
       * @description Status of the channel creation operation
       */
      status: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_DELETE_CHANNEL_SUBSCRIPTION tool input.
 */
type ABLY_DELETE_CHANNEL_SUBSCRIPTION_INPUT = {
  /**
   * Channel
   * @description The name of the channel to unsubscribe from. If not set, all subscriptions on all channels will be deleted.
   * @default null
   */
  channel: string | null;
  /**
   * Client Id
   * @description Filter to restrict to subscriptions associated with that clientId. Cannot be used with deviceId.
   * @default null
   */
  client_id: string | null;
  /**
   * Device Id
   * @description Filter to restrict to subscriptions for that deviceId. Cannot be used with clientId.
   * @default null
   */
  device_id: string | null;
};

/**
 * Type of ABLY's ABLY_DELETE_CHANNEL_SUBSCRIPTION tool output.
 */
type ABLY_DELETE_CHANNEL_SUBSCRIPTION_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Error
       * @description Error message if the operation failed
       * @default null
       */
      error: string | null;
      /**
       * Success
       * @description Indicates if the unsubscribe operation was successful
       */
      success: boolean;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_GET_CHANNEL_DETAILS tool input.
 */
type ABLY_GET_CHANNEL_DETAILS_INPUT = {
  /**
   * Channel Id
   * @description The ID of the channel to retrieve details for
   */
  channel_id?: string;
};

/**
 * Type of ABLY's ABLY_GET_CHANNEL_DETAILS tool output.
 */
type ABLY_GET_CHANNEL_DETAILS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Channel Id
       * @description The ID of the channel
       */
      channelId: string;
      /**
       * Status
       * @description Status information about the channel
       */
      status: {
          /**
           * Is Active
           * @description Whether the channel is currently active
           */
          isActive: boolean;
          /**
           * Occupancy
           * @description Occupancy information for the channel
           */
          occupancy: {
              /**
               * Metrics
               * @description Metrics about channel occupancy including connections, presence, publishers, and subscribers
               */
              metrics: {
                  /**
                   * Connections
                   * @description Total number of realtime connections attached to the channel
                   * @default 0
                   */
                  connections: number;
                  /**
                   * Object Publishers
                   * @description Number of connections publishing object updates
                   * @default 0
                   */
                  objectPublishers: number;
                  /**
                   * Object Subscribers
                   * @description Number of connections subscribed to object updates
                   * @default 0
                   */
                  objectSubscribers: number;
                  /**
                   * Presence Connections
                   * @description Number of connections permitted to enter presence on the channel
                   * @default 0
                   */
                  presenceConnections: number;
                  /**
                   * Presence Members
                   * @description Number of members in the presence set of the channel
                   * @default 0
                   */
                  presenceMembers: number;
                  /**
                   * Presence Subscribers
                   * @description Number of connections receiving presence messages on the channel
                   * @default 0
                   */
                  presenceSubscribers: number;
                  /**
                   * Publishers
                   * @description Number of connections permitted to publish messages to the channel
                   * @default 0
                   */
                  publishers: number;
                  /**
                   * Subscribers
                   * @description Number of connections receiving messages from the channel
                   * @default 0
                   */
                  subscribers: number;
              };
          };
      };
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_GET_CHANNEL_HISTORY tool input.
 */
type ABLY_GET_CHANNEL_HISTORY_INPUT = {
  /**
   * Channel Id
   * @description The ID of the channel to retrieve history for
   */
  channel_id?: string;
  /**
   * Direction
   * @description The direction of this query. The direction determines the order of the returned result array
   * @default backwards
   */
  direction: string | null;
  /**
   * End
   * @description The end of the query interval as a time in milliseconds since the epoch
   * @default null
   */
  end: number | null;
  /**
   * Limit
   * @description The maximum number of records to return. A limit greater than 1,000 is invalid
   * @default 100
   */
  limit: number | null;
  /**
   * Start
   * @description The start of the query interval as a time in milliseconds since the epoch
   * @default null
   */
  start: number | null;
};

/**
 * Type of ABLY's ABLY_GET_CHANNEL_HISTORY tool output.
 */
type ABLY_GET_CHANNEL_HISTORY_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Messages
       * @description Array of messages matching the query criteria
       */
      messages: {
          /**
           * Data
           * @description Message payload
           * @default null
           */
          data: string | null;
          /**
           * Id
           * @description Unique message ID
           */
          id: string;
          /**
           * Name
           * @description Event name
           * @default null
           */
          name: string | null;
          /**
           * Timestamp
           * @description Message timestamp in ms since epoch
           */
          timestamp: number;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_GET_PRESENCE_HISTORY tool input.
 */
type ABLY_GET_PRESENCE_HISTORY_INPUT = {
  /**
   * Channel Id
   * @description The channel name to get presence history for
   */
  channel_id?: string;
  /**
   * Direction
   * @description The direction of results. Can be either 'backwards' or 'forwards'.
   * @default backwards
   */
  direction: string | null;
  /**
   * End
   * @description The end of the query interval as a time in milliseconds since the epoch. Defaults to current time.
   * @default null
   */
  end: number | null;
  /**
   * Limit
   * @description The maximum number of records to return. Maximum value is 1000.
   * @default 100
   */
  limit: number | null;
  /**
   * Start
   * @description The start of the query interval as a time in milliseconds since the epoch
   * @default null
   */
  start: number | null;
};

/**
 * Type of ABLY's ABLY_GET_PRESENCE_HISTORY tool output.
 */
type ABLY_GET_PRESENCE_HISTORY_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Items
       * @description List of presence messages
       */
      items: {
          /**
           * Action
           * @description Presence state
           */
          action: number;
          /**
           * Client Id
           * @description Member client id provided by the client
           * @default null
           */
          clientId: string | null;
          /**
           * Connection Id
           * @description A unique connection id generated by Ably
           */
          connectionId: string;
          /**
           * Data
           * @description Optional client data provided by the client
           * @default null
           */
          data: unknown;
          /**
           * Id
           * @description A unique member identifier generated by Ably
           */
          id: string;
          /**
           * Timestamp
           * @description Message timestamp in ms since epoch
           */
          timestamp: number;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_GET_SERVICE_TIME tool input.
 */
type ABLY_GET_SERVICE_TIME_INPUT = object;

/**
 * Type of ABLY's ABLY_GET_SERVICE_TIME tool output.
 */
type ABLY_GET_SERVICE_TIME_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Time
       * @description Current server time in milliseconds since the epoch
       */
      time: number;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_GET_STATS tool input.
 */
type ABLY_GET_STATS_INPUT = {
  /**
   * Direction
   * @description The direction of this query. The direction determines the order of the returned result array
   * @default backwards
   */
  direction: string | null;
  /**
   * End
   * @description The end of the query interval as a time in milliseconds since the epoch
   * @default null
   */
  end: number | null;
  /**
   * Limit
   * @description The maximum number of records to return. A limit greater than 1,000 is invalid
   * @default 100
   */
  limit: number | null;
  /**
   * Start
   * @description The start of the query interval as a time in milliseconds since the epoch
   * @default null
   */
  start: number | null;
  /**
   * Unit
   * @description The unit of aggregation in the returned results
   * @default minute
   */
  unit: string | null;
};

/**
 * Type of ABLY's ABLY_GET_STATS tool output.
 */
type ABLY_GET_STATS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Stats
       * @description Array of stats records matching the query criteria
       */
      stats: {
          /**
           * Api Requests
           * @description API request stats
           * @default null
           */
          apiRequests: {
              [key: string]: unknown;
          } | null;
          /**
           * Channels
           * @description Channel stats
           * @default null
           */
          channels: {
              [key: string]: unknown;
          } | null;
          /**
           * Connections
           * @description Connection stats
           * @default null
           */
          connections: {
              [key: string]: unknown;
          } | null;
          /**
           * Inbound
           * @description Inbound message stats
           * @default null
           */
          inbound: {
              [key: string]: unknown;
          } | null;
          /**
           * Interval Id
           * @description The interval ID for these stats
           */
          intervalId: string;
          /**
           * Outbound
           * @description Outbound message stats
           * @default null
           */
          outbound: {
              [key: string]: unknown;
          } | null;
          /**
           * Persisted
           * @description Persisted message stats
           * @default null
           */
          persisted: {
              [key: string]: unknown;
          } | null;
          /**
           * Push
           * @description Push notification stats
           * @default null
           */
          push: {
              [key: string]: unknown;
          } | null;
          /**
           * Token Requests
           * @description Token request stats
           * @default null
           */
          tokenRequests: {
              [key: string]: unknown;
          } | null;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS tool input.
 */
type ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS_INPUT = {
  /**
   * Channel
   * @description Filter to restrict to subscriptions associated with that channel
   * @default null
   */
  channel: string | null;
  /**
   * Client Id
   * @description Filter to restrict to subscriptions associated with that clientId
   * @default null
   */
  client_id: string | null;
  /**
   * Concat Filters
   * @description Find all device registrations which match either clientId or deviceId
   * @default false
   */
  concat_filters: boolean | null;
  /**
   * Device Id
   * @description Filter to restrict to subscriptions for that deviceId
   * @default null
   */
  device_id: string | null;
  /**
   * Limit
   * @description The maximum number of records to return. A limit greater than 1,000 is invalid.
   * @default 100
   */
  limit: number | null;
};

/**
 * Type of ABLY's ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS tool output.
 */
type ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Items
       * @description List of channel subscriptions
       */
      items: {
          /**
           * Channel
           * @description The name of the channel
           */
          channel: string;
          /**
           * Client Id
           * @description The client ID associated with the subscription
           * @default null
           */
          client_id: string | null;
          /**
           * Device Id
           * @description The device ID associated with the subscription
           * @default null
           */
          device_id: string | null;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ABLY's ABLY_PUBLISH_MESSAGE_TO_CHANNEL tool input.
 */
type ABLY_PUBLISH_MESSAGE_TO_CHANNEL_INPUT = {
  /**
   * Channel Id
   * @description The name of the channel to publish the message to.
   */
  channel_id?: string;
  /**
   * Client Id
   * @description Optional client identifier to associate with the message.
   * @default null
   */
  client_id: string | null;
  /**
   * Event Name
   * @description Optional event name/type for the message.
   * @default null
   */
  event_name: string | null;
  /**
   * Message Data
   * @description The message payload. Can be a string or a JSON object.
   */
  message_data?: string | null;
  /**
   * Message Id
   * @description Optional unique message ID for idempotent publishing.
   * @default null
   */
  message_id: string | null;
  /**
   * Push Notification
   * @description Optional push notification configuration.
   * @default null
   */
  push_notification: {
      [key: string]: unknown;
  } | null;
};

/**
 * Type of ABLY's ABLY_PUBLISH_MESSAGE_TO_CHANNEL tool output.
 */
type ABLY_PUBLISH_MESSAGE_TO_CHANNEL_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Channel
       * @description The name of the channel the message was published to.
       */
      channel: string;
      /**
       * Message Id
       * @description The unique ID of the published message.
       */
      messageId: string;
      /**
       * Timestamp
       * @description The timestamp of the published message.
       * @default null
       */
      timestamp: number | null;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type map of all available tool input types for toolkit "ABLY".
 */
export type ABLY_TOOL_INPUTS = {
  BATCH_PRESENCE: ABLY_BATCH_PRESENCE_INPUT
  BATCH_PRESENCE_HISTORY: ABLY_BATCH_PRESENCE_HISTORY_INPUT
  CREATE_CHANNEL: ABLY_CREATE_CHANNEL_INPUT
  DELETE_CHANNEL_SUBSCRIPTION: ABLY_DELETE_CHANNEL_SUBSCRIPTION_INPUT
  GET_CHANNEL_DETAILS: ABLY_GET_CHANNEL_DETAILS_INPUT
  GET_CHANNEL_HISTORY: ABLY_GET_CHANNEL_HISTORY_INPUT
  GET_PRESENCE_HISTORY: ABLY_GET_PRESENCE_HISTORY_INPUT
  GET_SERVICE_TIME: ABLY_GET_SERVICE_TIME_INPUT
  GET_STATS: ABLY_GET_STATS_INPUT
  LIST_PUSH_CHANNEL_SUBSCRIPTIONS: ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS_INPUT
  PUBLISH_MESSAGE_TO_CHANNEL: ABLY_PUBLISH_MESSAGE_TO_CHANNEL_INPUT
}

/**
 * Type map of all available tool input types for toolkit "ABLY".
 */
export type ABLY_TOOL_OUTPUTS = {
  BATCH_PRESENCE: ABLY_BATCH_PRESENCE_OUTPUT
  BATCH_PRESENCE_HISTORY: ABLY_BATCH_PRESENCE_HISTORY_OUTPUT
  CREATE_CHANNEL: ABLY_CREATE_CHANNEL_OUTPUT
  DELETE_CHANNEL_SUBSCRIPTION: ABLY_DELETE_CHANNEL_SUBSCRIPTION_OUTPUT
  GET_CHANNEL_DETAILS: ABLY_GET_CHANNEL_DETAILS_OUTPUT
  GET_CHANNEL_HISTORY: ABLY_GET_CHANNEL_HISTORY_OUTPUT
  GET_PRESENCE_HISTORY: ABLY_GET_PRESENCE_HISTORY_OUTPUT
  GET_SERVICE_TIME: ABLY_GET_SERVICE_TIME_OUTPUT
  GET_STATS: ABLY_GET_STATS_OUTPUT
  LIST_PUSH_CHANNEL_SUBSCRIPTIONS: ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS_OUTPUT
  PUBLISH_MESSAGE_TO_CHANNEL: ABLY_PUBLISH_MESSAGE_TO_CHANNEL_OUTPUT
}

// ------------------- //
//    Trigger types    //
// ------------------- //



/**
 * Map of Composio's ABLY toolkit.
 */
export const ABLY = {
  slug: "ably",
  tools: {
    /**
     * This tool enables querying the presence states of multiple channels in a single api request. the api retrieves the member presence details of the specified channels in parallel.
     */
    BATCH_PRESENCE: "ABLY_BATCH_PRESENCE",
    /**
     * This tool enables querying presence history for multiple channels in a single api request. it uses the get endpoint at https://rest.ably.io/presence to retrieve the member presence history details of the specified channels in parallel.
     */
    BATCH_PRESENCE_HISTORY: "ABLY_BATCH_PRESENCE_HISTORY",
    /**
     * Creates a new channel or retrieves an existing channel in ably. this tool allows you to programmatically create and initialize channels for real-time messaging. since ably creates channels implicitly when first used, this action publishes an empty initialization message to create/activate the channel.
     */
    CREATE_CHANNEL: "ABLY_CREATE_CHANNEL",
    /**
     * This tool allows you to unsubscribe devices or clients from push notifications for specific channels. the operation is asynchronous, so immediate requests after deletion may briefly still return the subscription.
     */
    DELETE_CHANNEL_SUBSCRIPTION: "ABLY_DELETE_CHANNEL_SUBSCRIPTION",
    /**
     * This tool retrieves metadata and details for a specific channel in ably. it returns a channeldetails object containing information about the channel's status, occupancy, and other metadata. the endpoint provides visibility into channel activity, including metrics such as connections, presence, publishers, and subscribers, and requires appropriate permissions.
     */
    GET_CHANNEL_DETAILS: "ABLY_GET_CHANNEL_DETAILS",
    /**
     * This tool retrieves the message history for a specified ably channel. it uses the get /channels/{channelid}/messages endpoint to return a paginated list of messages in chronological order, subject to parameters such as 'channelid', 'limit', 'direction', 'start', and 'end'. the tool is useful for auditing, recovering missed messages, analyzing channel activity, and debugging message flows. authentication is required via basic or token authentication.
     */
    GET_CHANNEL_HISTORY: "ABLY_GET_CHANNEL_HISTORY",
    /**
     * This tool retrieves the history of presence messages for a specified channel in ably. it allows you to query presence events on a channel within a given time period.
     */
    GET_PRESENCE_HISTORY: "ABLY_GET_PRESENCE_HISTORY",
    /**
     * This tool retrieves the current server time from ably's service in milliseconds since the epoch. it is particularly useful for time synchronization and generating valid tokenrequest timestamps to prevent replay attacks. the endpoint supports multiple content types, handles http errors, network issues, and is a fundamental tool for ensuring accurate timing in ably applications.
     */
    GET_SERVICE_TIME: "ABLY_GET_SERVICE_TIME",
    /**
     * This tool retrieves your application's usage statistics from ably. the stats endpoint returns a paginated list of your application's usage statistics by minute, hour, day, or month. it supports optional parameters such as start, end, direction, limit, and unit to filter and format the returned data. the stats include metrics for: - message counts and data transferred - connection counts - channel usage - api request counts - push notification metrics - token request counts
     */
    GET_STATS: "ABLY_GET_STATS",
    /**
     * This tool retrieves a list of all push notification channel subscriptions. it allows you to view all active push notification subscriptions for channels in your ably application. allows filtering by channel, deviceid, and clientid, supports pagination with limit parameter, and returns detailed push notification subscription information including channel, deviceid, and clientid.
     */
    LIST_PUSH_CHANNEL_SUBSCRIPTIONS: "ABLY_LIST_PUSH_CHANNEL_SUBSCRIPTIONS",
    /**
     * This tool will allow users to publish a message to a specified ably channel using a post request. it covers the essentials like channel name, message data, optional event name/type, and additional metadata for push notifications. it is an independent and fundamental operation within ably's real-time messaging platform.
     */
    PUBLISH_MESSAGE_TO_CHANNEL: "ABLY_PUBLISH_MESSAGE_TO_CHANNEL",
  },
  triggerTypes: {},
}

/**
 * Type map of all available trigger payloads for toolkit "ABLY".
 */
export type ABLY_TRIGGER_PAYLOADS = {}

/**
 * Type map of all available trigger events for toolkit "ABLY".
 */
export type ABLY_TRIGGER_EVENTS = {}
