// --------------- //
//    Tool types   //
// --------------- //



/**
 * Type of APIVERVE's APIVERVE_ADVICE_GENERATOR tool input.
 */
type APIVERVE_ADVICE_GENERATOR_INPUT = object;

/**
 * Type of APIVERVE's APIVERVE_ADVICE_GENERATOR tool output.
 */
type APIVERVE_ADVICE_GENERATOR_OUTPUT = {
  /**
   * Data
   * @description Contains the advice payload.
   */
  data?: {
      /**
       * Advice
       * @description A random piece of advice generated by the API
       */
      advice: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Status of the API response, e.g., 'ok'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_AGE_CALCULATOR tool input.
 */
type APIVERVE_AGE_CALCULATOR_INPUT = {
  /**
   * Dob
   * Format: date
   * @description Date of birth in YYYY-MM-DD format
   */
  dob?: unknown;
};

/**
 * Type of APIVERVE's APIVERVE_AGE_CALCULATOR tool output.
 */
type APIVERVE_AGE_CALCULATOR_OUTPUT = {
  /**
   * Code
   * @description HTTP status code returned by the API
   */
  code?: number;
  /**
   * Data
   * @description Calculated age details
   */
  data?: {
      /**
       * Age Days
       * @description Total age in days since birth
       */
      age_days: number;
      /**
       * Age Months
       * @description Total age in months since birth
       */
      age_months: number;
      /**
       * Age Weeks
       * @description Total age in weeks since birth
       */
      age_weeks: number;
      /**
       * Age Words
       * @description Age expressed in human-readable words
       */
      age_words: {
          /**
           * Full
           * @description Full age description in words, e.g., 'thirty-five years old'
           */
          full: string;
          /**
           * Ordinal
           * @description Ordinal form of the age, e.g., 'thirty-fifth'
           */
          ordinal: string;
          /**
           * Years
           * @description Age in years written in words, e.g., 'thirty-five'
           */
          years: string;
      };
      /**
       * Age Years
       * @description Age in full years
       */
      age_years: number;
      /**
       * Dob
       * Format: date
       * @description Echo of the provided date of birth
       */
      dob: unknown;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Response status, e.g., 'ok'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_AIRLINE_LOOKUP_NAME tool input.
 */
type APIVERVE_AIRLINE_LOOKUP_NAME_INPUT = {
  /**
   * Accept
   * @description Response format. One of application/json, application/xml, or application/yaml. Defaults to application/json
   * @default null
   * @enum {string|null}
   */
  accept: "application/json" | "application/xml" | "application/yaml" | null;
  /**
   * Name
   * @description The full name of the airline to retrieve information for (e.g., 'American Airlines')
   */
  name?: string;
};

/**
 * Type of APIVERVE's APIVERVE_AIRLINE_LOOKUP_NAME tool output.
 */
type APIVERVE_AIRLINE_LOOKUP_NAME_OUTPUT = {
  /**
   * Code
   * @description HTTP status code of the response
   */
  code?: number;
  /**
   * Data
   * @description List of airline information objects
   */
  data?: {
      /**
       * Alias
       * @description Any alias the airline may have
       */
      Alias: string;
      /**
       * Callsign
       * @description The airline's callsign
       */
      Callsign: string;
      /**
       * Country
       * @description The country where the airline is based
       */
      Country: string;
      /**
       * Iata
       * @description The airline's IATA code
       */
      IATA: string;
      /**
       * Icao
       * @description The airline's ICAO code
       */
      ICAO: string;
      /**
       * Name
       * @description The airline's name
       */
      Name: string;
  }[];
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Response status, e.g., 'ok'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_AIRPORTS_LOOKUP_ICAO tool input.
 */
type APIVERVE_AIRPORTS_LOOKUP_ICAO_INPUT = {
  /**
   * Icao
   * @description The 4-letter ICAO code of the airport (e.g., 'KMCI')
   */
  icao?: string;
};

/**
 * Type of APIVERVE's APIVERVE_AIRPORTS_LOOKUP_ICAO tool output.
 */
type APIVERVE_AIRPORTS_LOOKUP_ICAO_OUTPUT = {
  /**
   * AirportData
   * @description Detailed airport information returned by the API.
   * @default null
   */
  data: {
      /**
       * City
       * @description City where the airport is located.
       */
      city: string;
      /**
       * City Info
       * @description Additional city metadata.
       */
      city_info: {
          /**
           * Alt Name
           * @description Alternative city name if available.
           */
          altName: string;
          /**
           * Country
           * @description Country code (ISO 3166-1 alpha-2).
           */
          country: string;
          /**
           * Name
           * @description City name.
           */
          name: string;
      };
      /**
       * Country
       * @description Country code.
       */
      country: string;
      /**
       * Elevation
       * @description Elevation in feet.
       */
      elevation: number;
      /**
       * Iata
       * @description IATA code of the airport.
       */
      iata: string;
      /**
       * Icao
       * @description ICAO code of the airport.
       */
      icao: string;
      /**
       * Lat
       * @description Latitude coordinate.
       */
      lat: number;
      /**
       * Lon
       * @description Longitude coordinate.
       */
      lon: number;
      /**
       * Name
       * @description Full name of the airport.
       */
      name: string;
      /**
       * State
       * @description State or region of the airport.
       */
      state: string;
      /**
       * Tz
       * @description IANA time-zone name.
       */
      tz: string;
  } | null;
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description API call status, e.g., 'ok'.
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_AIRPORT_DISTANCE_IATA tool input.
 */
type APIVERVE_AIRPORT_DISTANCE_IATA_INPUT = {
  /**
   * Iata1
   * @description The IATA code of the first airport (e.g. 'JFK')
   */
  iata1?: string;
  /**
   * Iata2
   * @description The IATA code of the second airport (e.g. 'LAX')
   */
  iata2?: string;
};

/**
 * Type of APIVERVE's APIVERVE_AIRPORT_DISTANCE_IATA tool output.
 */
type APIVERVE_AIRPORT_DISTANCE_IATA_OUTPUT = {
  /**
   * Data
   * @description Distance and airport details
   */
  data?: {
      /**
       * Airport1
       * @description Information about the first airport
       */
      airport1: {
          /**
           * City
           * @description City where the airport is located
           */
          city: string;
          /**
           * Country
           * @description Country of the airport
           */
          country: string;
          /**
           * Elevation
           * @description Elevation in feet
           */
          elevation: number;
          /**
           * Iata
           * @description IATA code of the airport
           */
          iata: string;
          /**
           * Icao
           * @description ICAO code of the airport
           */
          icao: string;
          /**
           * Latitude
           * @description Latitude of the airport
           */
          latitude: number;
          /**
           * Longitude
           * @description Longitude of the airport
           */
          longitude: number;
          /**
           * Name
           * @description Name of the airport
           */
          name: string;
          /**
           * State
           * @description State where the airport is located
           */
          state: string;
      };
      /**
       * Airport2
       * @description Information about the second airport
       */
      airport2: {
          /**
           * City
           * @description City where the airport is located
           */
          city: string;
          /**
           * Country
           * @description Country of the airport
           */
          country: string;
          /**
           * Elevation
           * @description Elevation in feet
           */
          elevation: number;
          /**
           * Iata
           * @description IATA code of the airport
           */
          iata: string;
          /**
           * Icao
           * @description ICAO code of the airport
           */
          icao: string;
          /**
           * Latitude
           * @description Latitude of the airport
           */
          latitude: number;
          /**
           * Longitude
           * @description Longitude of the airport
           */
          longitude: number;
          /**
           * Name
           * @description Name of the airport
           */
          name: string;
          /**
           * State
           * @description State where the airport is located
           */
          state: string;
      };
      /**
       * Distance Km
       * @description Distance in kilometers between the two airports
       */
      distanceKm: number;
      /**
       * Distance Miles
       * @description Distance in miles between the two airports
       */
      distanceMiles: number;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description API status, e.g., 'ok'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_AIR_QUALITY tool input.
 */
type APIVERVE_AIR_QUALITY_INPUT = {
  /**
   * City
   * @description The city name for which to get the air quality data (e.g., 'New York')
   */
  city?: string;
};

/**
 * Type of APIVERVE's APIVERVE_AIR_QUALITY tool output.
 */
type APIVERVE_AIR_QUALITY_OUTPUT = {
  /**
   * AirQualityData
   * @description Detailed air quality metrics returned for a city.
   * @default null
   */
  data: {
      /**
       * Carbon Monoxide
       * @description Carbon Monoxide (CO) concentration (µg/m³)
       */
      carbonMonoxide: number;
      /**
       * City
       * @description Echoed city name from the API
       */
      city: string;
      /**
       * Gb Defra Index
       * @description UK DEFRA air quality index (integer)
       */
      "gb-defra-index": number;
      /**
       * Nitrogen Dioxide
       * @description Nitrogen Dioxide (NO₂) concentration (µg/m³)
       */
      nitrogenDioxide: number;
      /**
       * Ozone
       * @description Ozone (O₃) concentration (µg/m³)
       */
      ozone: number;
      /**
       * Pm10
       * @description PM10 concentration (µg/m³)
       */
      pm10: number;
      /**
       * Pm2 5
       * @description PM2.5 concentration (µg/m³)
       */
      pm2_5: number;
      /**
       * Recommendation
       * @description Health recommendation based on current air quality
       */
      recommendation: string;
      /**
       * Sulfurdioxide
       * @description Sulfur Dioxide (SO₂) concentration (µg/m³)
       */
      sulfurdioxide: number;
      /**
       * Us Epa Index
       * @description US EPA air quality index (integer)
       */
      "us-epa-index": number;
  } | null;
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Request status: 'ok' or 'error'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_ANTONYM_FINDER tool input.
 */
type APIVERVE_ANTONYM_FINDER_INPUT = {
  /**
   * Word
   * @description The word to get the antonyms for
   */
  word?: string;
};

/**
 * Type of APIVERVE's APIVERVE_ANTONYM_FINDER tool output.
 */
type APIVERVE_ANTONYM_FINDER_OUTPUT = {
  /** Data */
  data?: {
      /**
       * Antonyms
       * @description List of antonyms for the given word
       */
      antonyms: string[];
      /**
       * Word
       * @description The queried word
       */
      word: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Response status, e.g., 'ok'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_APP_STORE_SCRAPER tool input.
 */
type APIVERVE_APP_STORE_SCRAPER_INPUT = {
  /**
   * Appid
   * @description The App Store app ID (digits only)
   */
  appid?: string;
  /**
   * Country
   * @description ISO 3166-1 alpha-2 country code (e.g., 'us')
   */
  country?: string;
};

/**
 * Type of APIVERVE's APIVERVE_APP_STORE_SCRAPER tool output.
 */
type APIVERVE_APP_STORE_SCRAPER_OUTPUT = {
  /**
   * Data
   * @description Payload containing detailed app metadata
   */
  data?: {
      /**
       * App Id
       * @description Bundle identifier of the app
       */
      appId: string;
      /**
       * Appletv Screenshots
       * @description List of Apple TV screenshot URLs
       */
      appletvScreenshots: string[];
      /**
       * Content Rating
       * @description Content rating (e.g., '4+')
       */
      contentRating: string;
      /**
       * Currency
       * @description Currency code, e.g., 'USD'
       */
      currency: string;
      /**
       * Current Version Reviews
       * @description Number of reviews for current version
       */
      currentVersionReviews: number;
      /**
       * Current Version Score
       * @description Average rating for current version
       */
      currentVersionScore: number;
      /**
       * Description
       * @description Full description of the app
       */
      description: string;
      /**
       * Developer
       * @description Developer name
       */
      developer: string;
      /**
       * Developer Id
       * @description Developer identifier
       */
      developerId: number;
      /**
       * Developer Url
       * @description Developer's App Store page URL
       */
      developerUrl: string;
      /**
       * Developer Website
       * @description Developer's external website URL
       */
      developerWebsite: string;
      /**
       * Free
       * @description True if the app is free to download
       */
      free: boolean;
      /**
       * Genre Ids
       * @description List of genre identifier strings
       */
      genreIds: string[];
      /**
       * Genres
       * @description List of genre names
       */
      genres: string[];
      /**
       * Icon
       * @description URL to the app icon image
       */
      icon: string;
      /**
       * Id
       * @description Numeric app identifier
       */
      id: number;
      /**
       * Ipad Screenshots
       * @description List of iPad screenshot URLs
       */
      ipadScreenshots: string[];
      /**
       * Languages
       * @description Supported language codes
       */
      languages: string[];
      /**
       * Price
       * @description Price in the smallest currency unit, e.g., cents
       */
      price: number;
      /**
       * Primary Genre
       * @description Primary genre name
       */
      primaryGenre: string;
      /**
       * Primary Genre Id
       * @description Primary genre identifier
       */
      primaryGenreId: number;
      /**
       * Release Notes
       * @description Release notes for the current version
       */
      releaseNotes: string;
      /**
       * Released
       * @description Original release timestamp in ISO 8601 format
       */
      released: string;
      /**
       * Required Os Version
       * @description Minimum required OS version
       */
      requiredOsVersion: string;
      /**
       * Reviews
       * @description Total number of reviews
       */
      reviews: number;
      /**
       * Score
       * @description Average user rating (0.0–5.0)
       */
      score: number;
      /**
       * Screenshots
       * @description List of iPhone screenshot URLs
       */
      screenshots: string[];
      /**
       * Size
       * @description Size of the app in bytes
       */
      size: string;
      /**
       * Supported Devices
       * @description List of supported device identifiers
       */
      supportedDevices: string[];
      /**
       * Title
       * @description App title
       */
      title: string;
      /**
       * Updated
       * @description Last update timestamp in ISO 8601 format
       */
      updated: string;
      /**
       * Url
       * @description App Store URL for the app
       */
      url: string;
      /**
       * Version
       * @description Current version string
       */
      version: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Response status, 'ok' or 'error'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_CURRENCY_CONVERTER tool input.
 */
type APIVERVE_CURRENCY_CONVERTER_INPUT = {
  /**
   * Amount
   * @description Amount in source currency to convert. Must be non-negative.
   */
  amount?: number;
  /**
   * From Currency
   * @description The ISO currency code to convert from, e.g., 'USD'
   */
  from_currency?: string;
  /**
   * To Currency
   * @description The ISO currency code to convert to, e.g., 'EUR'
   */
  to_currency?: string;
};

/**
 * Type of APIVERVE's APIVERVE_CURRENCY_CONVERTER tool output.
 */
type APIVERVE_CURRENCY_CONVERTER_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Amount
       * @description Original amount in source currency
       */
      amount: number;
      /**
       * Converted
       * @description Converted amount in target currency
       */
      converted: number;
      /**
       * From Currency
       * @description Source currency code used in the request
       */
      from_currency: string;
      /**
       * Rate
       * @description Exchange rate used for conversion
       */
      rate: number;
      /**
       * To Currency
       * @description Target currency code used in the request
       */
      to_currency: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_DICTIONARY tool input.
 */
type APIVERVE_DICTIONARY_INPUT = {
  /**
   * Word
   * @description The word for which you want to get the definition (e.g., apple)
   */
  word?: string;
};

/**
 * Type of APIVERVE's APIVERVE_DICTIONARY tool output.
 */
type APIVERVE_DICTIONARY_OUTPUT = {
  /**
   * Data
   * @description Data object containing word and definitions
   */
  data?: {
      /**
       * Definition Count
       * @description Number of definitions returned
       */
      definitionCount: number;
      /**
       * Definitions
       * @description List of definitions for the word
       */
      definitions: string[];
      /**
       * Word
       * @description The word that was defined
       */
      word: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Status of the API response
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of APIVERVE's APIVERVE_WEATHER_BY_CITY tool input.
 */
type APIVERVE_WEATHER_BY_CITY_INPUT = {
  /**
   * Accept
   * @description Optional. Desired response format. One of 'application/json', 'application/xml', 'application/yaml'. Defaults to 'application/json'.
   * @default null
   * @enum {string|null}
   */
  accept: "application/json" | "application/xml" | "application/yaml" | null;
  /**
   * City
   * @description Name of the city to retrieve current weather for (e.g., 'San Francisco')
   */
  city?: string;
};

/**
 * Type of APIVERVE's APIVERVE_WEATHER_BY_CITY tool output.
 */
type APIVERVE_WEATHER_BY_CITY_OUTPUT = {
  /**
   * WeatherData
   * @description Detailed weather metrics returned for a city.
   * @default null
   */
  data: {
      /**
       * Feelslike C
       * @description Feels-like temperature in degrees Celsius
       */
      feelslikeC: number;
      /**
       * Feelslike F
       * @description Feels-like temperature in degrees Fahrenheit
       */
      feelslikeF: number;
      /**
       * Gust Kph
       * @description Wind gust speed in kilometers per hour
       */
      gustKph: number;
      /**
       * Gust Mph
       * @description Wind gust speed in miles per hour
       */
      gustMph: number;
      /**
       * Precip In
       * @description Precipitation amount in inches
       */
      precipIn: number;
      /**
       * Precip Mm
       * @description Precipitation amount in millimeters
       */
      precipMm: number;
      /**
       * Pressure In
       * @description Atmospheric pressure in inches
       */
      pressureIn: number;
      /**
       * Pressure Mb
       * @description Atmospheric pressure in millibars
       */
      pressureMb: number;
      /**
       * Temp C
       * @description Temperature in degrees Celsius
       */
      tempC: number;
      /**
       * Temp F
       * @description Temperature in degrees Fahrenheit
       */
      tempF: number;
      /**
       * Vis Km
       * @description Visibility in kilometers
       */
      visKm: number;
      /**
       * Vis Miles
       * @description Visibility in miles
       */
      visMiles: number;
      /**
       * Wind Degree
       * @description Wind direction in degrees
       */
      windDegree: number;
      /**
       * Wind Dir
       * @description Wind direction as compass point, e.g., 'NW'
       */
      windDir: string;
      /**
       * Wind Kph
       * @description Wind speed in kilometers per hour
       */
      windKph: number;
      /**
       * Wind Mph
       * @description Wind speed in miles per hour
       */
      windMph: number;
  } | null;
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Status
   * @description Request status: 'ok' or 'error'
   */
  status?: string;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type map of all available tool input types for toolkit "APIVERVE".
 */
export type APIVERVE_TOOL_INPUTS = {
  ADVICE_GENERATOR: APIVERVE_ADVICE_GENERATOR_INPUT
  AGE_CALCULATOR: APIVERVE_AGE_CALCULATOR_INPUT
  AIRLINE_LOOKUP_NAME: APIVERVE_AIRLINE_LOOKUP_NAME_INPUT
  AIRPORTS_LOOKUP_ICAO: APIVERVE_AIRPORTS_LOOKUP_ICAO_INPUT
  AIRPORT_DISTANCE_IATA: APIVERVE_AIRPORT_DISTANCE_IATA_INPUT
  AIR_QUALITY: APIVERVE_AIR_QUALITY_INPUT
  ANTONYM_FINDER: APIVERVE_ANTONYM_FINDER_INPUT
  APP_STORE_SCRAPER: APIVERVE_APP_STORE_SCRAPER_INPUT
  CURRENCY_CONVERTER: APIVERVE_CURRENCY_CONVERTER_INPUT
  DICTIONARY: APIVERVE_DICTIONARY_INPUT
  WEATHER_BY_CITY: APIVERVE_WEATHER_BY_CITY_INPUT
}

/**
 * Type map of all available tool input types for toolkit "APIVERVE".
 */
export type APIVERVE_TOOL_OUTPUTS = {
  ADVICE_GENERATOR: APIVERVE_ADVICE_GENERATOR_OUTPUT
  AGE_CALCULATOR: APIVERVE_AGE_CALCULATOR_OUTPUT
  AIRLINE_LOOKUP_NAME: APIVERVE_AIRLINE_LOOKUP_NAME_OUTPUT
  AIRPORTS_LOOKUP_ICAO: APIVERVE_AIRPORTS_LOOKUP_ICAO_OUTPUT
  AIRPORT_DISTANCE_IATA: APIVERVE_AIRPORT_DISTANCE_IATA_OUTPUT
  AIR_QUALITY: APIVERVE_AIR_QUALITY_OUTPUT
  ANTONYM_FINDER: APIVERVE_ANTONYM_FINDER_OUTPUT
  APP_STORE_SCRAPER: APIVERVE_APP_STORE_SCRAPER_OUTPUT
  CURRENCY_CONVERTER: APIVERVE_CURRENCY_CONVERTER_OUTPUT
  DICTIONARY: APIVERVE_DICTIONARY_OUTPUT
  WEATHER_BY_CITY: APIVERVE_WEATHER_BY_CITY_OUTPUT
}

// ------------------- //
//    Trigger types    //
// ------------------- //



/**
 * Map of Composio's APIVERVE toolkit.
 */
export const APIVERVE = {
  slug: "apiverve",
  tools: {
    /**
     * Tool to generate a random piece of advice. use when you need spontaneous guidance or motivation.
     */
    ADVICE_GENERATOR: "APIVERVE_ADVICE_GENERATOR",
    /**
     * Tool to calculate age from date of birth. use when you need a breakdown of years, months, weeks, and days from a given dob. example: "calculate age for dob=1990-01-01"
     */
    AGE_CALCULATOR: "APIVERVE_AGE_CALCULATOR",
    /**
     * Tool to get airline info by name. use after obtaining the official airline name.
     */
    AIRLINE_LOOKUP_NAME: "APIVERVE_AIRLINE_LOOKUP_NAME",
    /**
     * Tool to get airport information by icao code. use when you have a valid 4-letter icao code and need detailed airport information.
     */
    AIRPORTS_LOOKUP_ICAO: "APIVERVE_AIRPORTS_LOOKUP_ICAO",
    /**
     * Tool to get distance between two airports by their iata codes. use when you have valid airport iata codes and need the flight distance.
     */
    AIRPORT_DISTANCE_IATA: "APIVERVE_AIRPORT_DISTANCE_IATA",
    /**
     * Tool to get air quality data for a city. use when you need current aqi, pollutant levels, and a health recommendation.
     */
    AIR_QUALITY: "APIVERVE_AIR_QUALITY",
    /**
     * Tool to get antonyms for a word. use when you need opposite terms for text analysis.
     */
    ANTONYM_FINDER: "APIVERVE_ANTONYM_FINDER",
    /**
     * Tool to fetch detailed app metadata from the app store. use when you have a valid app store app id and country code.
     */
    APP_STORE_SCRAPER: "APIVERVE_APP_STORE_SCRAPER",
    /**
     * Tool to convert currency rates. use when you need to convert an amount between two currencies with the latest exchange rate.
     */
    CURRENCY_CONVERTER: "APIVERVE_CURRENCY_CONVERTER",
    /**
     * Tool to get the definition of a word. use when you need to find the meaning of a specific word. e.g., "define the word apple."
     */
    DICTIONARY: "APIVERVE_DICTIONARY",
    /**
     * Tool to get current weather by city. use when you need to obtain up-to-date weather details for a specific city after confirming the city name. example: "what's the weather in berlin?"
     */
    WEATHER_BY_CITY: "APIVERVE_WEATHER_BY_CITY",
  },
  triggerTypes: {},
}

/**
 * Type map of all available trigger payloads for toolkit "APIVERVE".
 */
export type APIVERVE_TRIGGER_PAYLOADS = {}

/**
 * Type map of all available trigger events for toolkit "APIVERVE".
 */
export type APIVERVE_TRIGGER_EVENTS = {}
