// --------------- //
//    Tool types   //
// --------------- //



/**
 * Type of FLOWISEAI's FLOWISEAI_CLONE_CHATFLOW tool input.
 */
type FLOWISEAI_CLONE_CHATFLOW_INPUT = {
  /**
   * Id
   * @description UUID of the chatflow to clone
   */
  id?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_CLONE_CHATFLOW tool output.
 */
type FLOWISEAI_CLONE_CHATFLOW_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Analytic
       * @description Analytics configuration/data.
       * @default null
       */
      analytic: string | null;
      /**
       * Api Config
       * @description API configuration.
       * @default null
       */
      apiConfig: string | null;
      /**
       * Apikeyid
       * @description API key identifier.
       * @default null
       */
      apikeyid: string | null;
      /**
       * Category
       * @description Categories (semicolon-delimited).
       * @default null
       */
      category: string | null;
      /**
       * Chatbot Config
       * @description Chatbot configuration.
       * @default null
       */
      chatbotConfig: string | null;
      /**
       * Created Date
       * Format: date-time
       * @description Creation timestamp.
       */
      createdDate: string;
      /**
       * Deployed
       * @description Deployment status.
       */
      deployed: boolean;
      /**
       * Flow Data
       * @description Flow data payload.
       */
      flowData: string;
      /**
       * Id
       * @description Chatflow ID.
       */
      id: string;
      /**
       * Is Public
       * @description Public visibility flag.
       */
      isPublic: boolean;
      /**
       * Name
       * @description Chatflow name.
       */
      name: string;
      /**
       * Speech To Text
       * @description Speech-to-text configuration.
       * @default null
       */
      speechToText: string | null;
      /**
       * Type
       * @description Chatflow type.
       * @enum {string}
       */
      type: "CHATFLOW" | "MULTIAGENT";
      /**
       * Updated Date
       * Format: date-time
       * @description Last update timestamp.
       */
      updatedDate: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_CREATE_CHATFLOW tool input.
 */
type FLOWISEAI_CREATE_CHATFLOW_INPUT = {
  /**
   * Analytic
   * @description JSON string for analytics settings.
   * @default null
   */
  analytic: string | null;
  /**
   * Api Config
   * @description JSON string for external API configuration.
   * @default null
   */
  apiConfig: string | null;
  /**
   * Apikeyid
   * @description API key identifier to attach to this chatflow.
   * @default null
   */
  apikeyid: string | null;
  /**
   * Category
   * @description Semicolon-delimited categories, e.g., 'support;sales'.
   * @default null
   */
  category: string | null;
  /**
   * Chatbot Config
   * @description JSON string for chatbot-specific configuration.
   * @default null
   */
  chatbotConfig: string | null;
  /**
   * Created Date
   * Format: date-time
   * @description ISO 8601 timestamp for creation; server overrides if omitted.
   * @default null
   */
  createdDate: string | null;
  /**
   * Deployed
   * @description Whether the chatflow should be deployed immediately.
   * @default null
   */
  deployed: boolean | null;
  /**
   * Flow Data
   * @description JSON string representing the flow definition.
   * @default null
   */
  flowData: string | null;
  /**
   * Id
   * @description UUID of the chatflow. Generated by server if omitted.
   * @default null
   */
  id: string | null;
  /**
   * Is Public
   * @description Make the chatflow public if true.
   * @default null
   */
  isPublic: boolean | null;
  /**
   * Name
   * @description Name for the chatflow.
   * @default null
   */
  name: string | null;
  /**
   * Speech To Text
   * @description JSON string for speech-to-text configuration.
   * @default null
   */
  speechToText: string | null;
  /**
   * Type
   * @description Type of chatflow.
   * @default null
   * @enum {string|null}
   */
  type: "CHATFLOW" | "MULTIAGENT" | null;
  /**
   * Updated Date
   * Format: date-time
   * @description ISO 8601 timestamp for last update; server overrides if omitted.
   * @default null
   */
  updatedDate: string | null;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_CREATE_CHATFLOW tool output.
 */
type FLOWISEAI_CREATE_CHATFLOW_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Analytic
       * @description Analytics configuration/data.
       * @default null
       */
      analytic: string | null;
      /**
       * Api Config
       * @description API configuration.
       * @default null
       */
      apiConfig: string | null;
      /**
       * Apikeyid
       * @description API key identifier.
       * @default null
       */
      apikeyid: string | null;
      /**
       * Category
       * @description Categories (semicolon-delimited).
       * @default null
       */
      category: string | null;
      /**
       * Chatbot Config
       * @description Chatbot configuration.
       * @default null
       */
      chatbotConfig: string | null;
      /**
       * Created Date
       * Format: date-time
       * @description Creation timestamp.
       */
      createdDate: string;
      /**
       * Deployed
       * @description Deployment status.
       */
      deployed: boolean;
      /**
       * Flow Data
       * @description Flow data payload.
       */
      flowData: string;
      /**
       * Id
       * @description Chatflow ID.
       */
      id: string;
      /**
       * Is Public
       * @description Public visibility flag.
       */
      isPublic: boolean;
      /**
       * Name
       * @description Chatflow name.
       */
      name: string;
      /**
       * Speech To Text
       * @description Speech-to-text configuration.
       * @default null
       */
      speechToText: string | null;
      /**
       * Type
       * @description Chatflow type.
       * @enum {string}
       */
      type: "CHATFLOW" | "MULTIAGENT";
      /**
       * Updated Date
       * Format: date-time
       * @description Last update timestamp.
       */
      updatedDate: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_DELETE_CHATFLOW tool input.
 */
type FLOWISEAI_DELETE_CHATFLOW_INPUT = {
  /**
   * Id
   * @description Chatflow ID to delete
   */
  id?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_DELETE_CHATFLOW tool output.
 */
type FLOWISEAI_DELETE_CHATFLOW_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: Record<string, never>;
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_DELETE_CHAT_MESSAGES tool input.
 */
type FLOWISEAI_DELETE_CHAT_MESSAGES_INPUT = {
  /**
   * Chat Id
   * @description Filter by specific chat ID
   * @default null
   */
  chatId: string | null;
  /**
   * Chat Type
   * @description Filter by chat type
   * @default null
   * @enum {string|null}
   */
  chatType: "INTERNAL" | "EXTERNAL" | null;
  /**
   * End Date
   * @description ISO-8601 end timestamp, e.g., 2025-01-13T11:28:36.000Z
   * @default null
   */
  endDate: string | null;
  /**
   * Feedback Type
   * @description Filter by feedback type
   * @default null
   * @enum {string|null}
   */
  feedbackType: "THUMBS_UP" | "THUMBS_DOWN" | null;
  /**
   * Hard Delete
   * @description Whether to perform hard delete including third-party storage
   * @default false
   */
  hardDelete: boolean | null;
  /**
   * Id
   * @description Chatflow ID to delete messages from
   */
  id?: string;
  /**
   * Memory Type
   * @description Filter by memory type, e.g., 'Buffer Memory'
   * @default null
   */
  memoryType: string | null;
  /**
   * Session Id
   * @description Filter by session ID
   * @default null
   */
  sessionId: string | null;
  /**
   * Start Date
   * @description ISO-8601 start timestamp, e.g., 2025-01-01T11:28:36.000Z
   * @default null
   */
  startDate: string | null;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_DELETE_CHAT_MESSAGES tool output.
 */
type FLOWISEAI_DELETE_CHAT_MESSAGES_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Message
       * @description Additional details about the deletion
       * @default null
       */
      message: string | null;
      /**
       * Success
       * @description Indicates if the deletion was successful
       */
      success: boolean;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_DELETE_TOOL_BY_ID tool input.
 */
type FLOWISEAI_DELETE_TOOL_BY_ID_INPUT = {
  /**
   * Id
   * @description Tool ID to delete
   */
  id?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_DELETE_TOOL_BY_ID tool output.
 */
type FLOWISEAI_DELETE_TOOL_BY_ID_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: Record<string, never>;
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_EXPORT_CHATFLOW tool input.
 */
type FLOWISEAI_EXPORT_CHATFLOW_INPUT = {
  /**
   * Id
   * @description Unique identifier of the chatflow to export
   */
  id?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_EXPORT_CHATFLOW tool output.
 */
type FLOWISEAI_EXPORT_CHATFLOW_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Description
       * @description Description of the chatflow
       * @default null
       */
      description: string | null;
      /**
       * Edges
       * @description List of edges connecting nodes
       */
      edges: {
          [key: string]: unknown;
      }[];
      /**
       * Id
       * @description ID of the chatflow
       */
      id: string;
      /**
       * Metadata
       * @description Additional metadata of the chatflow
       * @default null
       */
      metadata: {
          [key: string]: unknown;
      } | null;
      /**
       * Name
       * @description Name of the chatflow
       */
      name: string;
      /**
       * Nodes
       * @description List of nodes in the chatflow
       */
      nodes: {
          [key: string]: unknown;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_GET_ALL_CHATFLOWS tool input.
 */
type FLOWISEAI_GET_ALL_CHATFLOWS_INPUT = object;

/**
 * Type of FLOWISEAI's FLOWISEAI_GET_ALL_CHATFLOWS tool output.
 */
type FLOWISEAI_GET_ALL_CHATFLOWS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Chatflows
       * @description List of all chatflow objects.
       */
      chatflows: {
          /**
           * Analytic
           * @description Serialized analytics configuration JSON.
           */
          analytic: string;
          /**
           * Api Config
           * @description Serialized API configuration JSON.
           */
          apiConfig: string;
          /**
           * Apikeyid
           * @description API key ID associated with this chatflow.
           */
          apikeyid: string;
          /**
           * Category
           * @description Semicolon-separated list of categories.
           */
          category: string;
          /**
           * Chatbot Config
           * @description Serialized chatbot configuration JSON.
           */
          chatbotConfig: string;
          /**
           * Created Date
           * Format: date-time
           * @description ISO 8601 timestamp when created.
           */
          createdDate: string;
          /**
           * Deployed
           * @description True if the chatflow is deployed.
           */
          deployed: boolean;
          /**
           * Flow Data
           * @description Serialized flow data JSON.
           */
          flowData: string;
          /**
           * Id
           * @description Unique identifier of the chatflow.
           */
          id: string;
          /**
           * Is Public
           * @description True if the chatflow is public.
           */
          isPublic: boolean;
          /**
           * Name
           * @description Name of the chatflow.
           */
          name: string;
          /**
           * Speech To Text
           * @description Serialized speech-to-text configuration JSON.
           */
          speechToText: string;
          /**
           * Type
           * @description Type of chatflow: CHATFLOW or MULTIAGENT.
           * @enum {string}
           */
          type: "CHATFLOW" | "MULTIAGENT";
          /**
           * Updated Date
           * Format: date-time
           * @description ISO 8601 timestamp when last updated.
           */
          updatedDate: string;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_GET_SINGLE_CHATFLOW tool input.
 */
type FLOWISEAI_GET_SINGLE_CHATFLOW_INPUT = {
  /**
   * Id
   * @description Unique identifier of the chatflow to retrieve
   */
  id?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_GET_SINGLE_CHATFLOW tool output.
 */
type FLOWISEAI_GET_SINGLE_CHATFLOW_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Analytic
       * @description Analytics configuration or metadata
       */
      analytic: string;
      /**
       * Api Config
       * @description API integration settings
       */
      apiConfig: string;
      /**
       * Apikeyid
       * @description API key ID associated with the chatflow
       */
      apikeyid: string;
      /**
       * Category
       * @description Category of the chatflow
       */
      category: string;
      /**
       * Chatbot Config
       * @description Configuration details for the chatbot
       */
      chatbotConfig: string;
      /**
       * Created Date
       * @description ISO timestamp when the chatflow was created
       */
      createdDate: string;
      /**
       * Deployed
       * @description Whether the chatflow is deployed
       */
      deployed: boolean;
      /**
       * Flow Data
       * @description Raw flow data JSON as string
       */
      flowData: string;
      /**
       * Id
       * @description Unique identifier of the chatflow
       */
      id: string;
      /**
       * Is Public
       * @description Whether the chatflow is publicly accessible
       */
      isPublic: boolean;
      /**
       * Name
       * @description Name of the chatflow
       */
      name: string;
      /**
       * Speech To Text
       * @description Speech-to-text settings, if any
       */
      speechToText: string;
      /**
       * Type
       * @description Type of chatflow, e.g., CHATFLOW or MULTIAGENT
       */
      type: string;
      /**
       * Updated Date
       * @description ISO timestamp when the chatflow was last updated
       */
      updatedDate: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_GET_TOOL_BY_ID tool input.
 */
type FLOWISEAI_GET_TOOL_BY_ID_INPUT = {
  /**
   * Id
   * @description Unique identifier of the tool to retrieve
   */
  id?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_GET_TOOL_BY_ID tool output.
 */
type FLOWISEAI_GET_TOOL_BY_ID_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Color
       * @description Hexadecimal color code for the tool
       */
      color: string;
      /**
       * Created Date
       * @description ISO 8601 timestamp when the tool was created
       */
      createdDate: string;
      /**
       * Description
       * @description Description of the tool
       */
      description: string;
      /**
       * Func
       * @description Functionality description or code for the tool, if any
       * @default null
       */
      func: string | null;
      /**
       * Icon Src
       * @description URL of the tool's icon, if available
       * @default null
       */
      iconSrc: string | null;
      /**
       * Id
       * @description Unique identifier for the tool (UUID)
       */
      id: string;
      /**
       * Name
       * @description Name of the tool
       */
      name: string;
      /**
       * Schema
       * @description JSON schema associated with the tool, if any
       * @default null
       */
      schema: string | null;
      /**
       * Updated Date
       * @description ISO 8601 timestamp when the tool was last updated
       */
      updatedDate: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_IMPORT_CHATFLOW tool input.
 */
type FLOWISEAI_IMPORT_CHATFLOW_INPUT = {
  /**
   * Content
   * @description JSON string content of the exported chatflow
   */
  content?: string;
  /**
   * Filename
   * @description Name of the JSON file to import, e.g., 'chatflow.json'
   */
  filename?: string;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_IMPORT_CHATFLOW tool output.
 */
type FLOWISEAI_IMPORT_CHATFLOW_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Description
       * @description Description of the chatflow
       * @default null
       */
      description: string | null;
      /**
       * Edges
       * @description List of edges in the chatflow
       */
      edges: {
          [key: string]: unknown;
      }[];
      /**
       * Id
       * @description UUID of the imported chatflow
       */
      id: string;
      /**
       * Metadata
       * @description Additional metadata of the chatflow
       * @default null
       */
      metadata: {
          [key: string]: unknown;
      } | null;
      /**
       * Name
       * @description Name of the imported chatflow
       */
      name: string;
      /**
       * Nodes
       * @description List of nodes in the chatflow
       */
      nodes: {
          [key: string]: unknown;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_LIST_ALL_TOOLS tool input.
 */
type FLOWISEAI_LIST_ALL_TOOLS_INPUT = object;

/**
 * Type of FLOWISEAI's FLOWISEAI_LIST_ALL_TOOLS tool output.
 */
type FLOWISEAI_LIST_ALL_TOOLS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Tools
       * @description List of tool objects returned by the API.
       */
      tools: {
          /**
           * Color
           * @description Color associated with the tool.
           */
          color: string;
          /**
           * Created Date
           * Format: date-time
           * @description ISO 8601 timestamp when the tool was created.
           */
          createdDate: string;
          /**
           * Description
           * @description Description of the tool.
           */
          description: string;
          /**
           * Func
           * @description Functionality or code details of the tool.
           * @default null
           */
          func: string | null;
          /**
           * Icon Src
           * @description Source URL for the tool's icon.
           * @default null
           */
          iconSrc: string | null;
          /**
           * Id
           * @description Unique identifier for the tool.
           */
          id: string;
          /**
           * Name
           * @description Name of the tool.
           */
          name: string;
          /**
           * Schema
           * @description JSON schema associated with the tool.
           * @default null
           */
          schema: string | null;
          /**
           * Updated Date
           * Format: date-time
           * @description ISO 8601 timestamp when the tool was last updated.
           */
          updatedDate: string;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_LIST_CHAT_MESSAGES tool input.
 */
type FLOWISEAI_LIST_CHAT_MESSAGES_INPUT = {
  /**
   * Chat Id
   * @description Filter by specific chat session ID
   * @default null
   */
  chatId: string | null;
  /**
   * Chat Type
   * @description Filter by chat type. Values: INTERNAL or EXTERNAL
   * @default null
   * @enum {string|null}
   */
  chatType: "INTERNAL" | "EXTERNAL" | null;
  /**
   * End Date
   * Format: date-time
   * @description Filter messages created on or before this ISO 8601 date-time
   * @default null
   */
  endDate: unknown;
  /**
   * Feedback
   * @description Filter by whether feedback was provided
   * @default null
   */
  feedback: boolean | null;
  /**
   * Feedback Type
   * @description Filter by type of feedback when feedback=true. Values: THUMBS_UP or THUMBS_DOWN
   * @default null
   * @enum {string|null}
   */
  feedbackType: "THUMBS_UP" | "THUMBS_DOWN" | null;
  /**
   * Id
   * @description Chatflow ID to retrieve messages for
   */
  id?: string;
  /**
   * Memory Type
   * @description Filter by memory type, e.g., 'Buffer Memory'
   * @default null
   */
  memoryType: string | null;
  /**
   * Order
   * @description Sort order of messages. Values: ASC or DESC
   * @default null
   * @enum {string|null}
   */
  order: "ASC" | "DESC" | null;
  /**
   * Session Id
   * @description Filter by session identifier
   * @default null
   */
  sessionId: string | null;
  /**
   * Start Date
   * Format: date-time
   * @description Filter messages created on or after this ISO 8601 date-time
   * @default null
   */
  startDate: unknown;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_LIST_CHAT_MESSAGES tool output.
 */
type FLOWISEAI_LIST_CHAT_MESSAGES_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Messages
       * @description List of chat messages retrieved
       */
      messages: {
          /**
           * Action
           * @description Actions taken or available on the message
           */
          action: {
              /**
               * Elements
               * @description Elements involved in the action
               */
              elements: {
                  [key: string]: unknown;
              }[];
              /**
               * Id
               * @description Identifier of the action
               */
              id: string;
              /**
               * Mapping
               * @description Mapping details for the action
               */
              mapping: {
                  /**
                   * Approve
                   * @description Approval status of the action
                   */
                  approve: boolean;
                  /**
                   * Reject
                   * @description Rejection status of the action
                   */
                  reject: boolean;
                  /**
                   * Tool Calls
                   * @description List of tool calls in the action mapping
                   */
                  toolCalls: {
                      /**
                       * Tool
                       * @description Name of the tool used
                       */
                      tool: string;
                      /**
                       * Tool Input
                       * @description Input parameters passed to the tool
                       */
                      toolInput: {
                          [key: string]: unknown;
                      };
                      /**
                       * Tool Output
                       * @description Output returned by the tool
                       */
                      toolOutput: string;
                  }[];
              };
          }[];
          /**
           * Agent Reasoning
           * @description Detailed reasoning traces of the agent
           */
          agentReasoning: {
              /**
               * Agent Name
               * @description Name of the agent
               */
              agentName: string;
              /**
               * Messages
               * @description Messages from the agent reasoning
               */
              messages: string[];
              /**
               * Node Id
               * @description Identifier of the node
               */
              nodeId: string;
              /**
               * Node Name
               * @description Node name where reasoning occurred
               */
              nodeName: string;
              /**
               * Source Documents
               * @description Documents referenced during reasoning
               */
              sourceDocuments: {
                  /**
                   * Metadata
                   * @description Arbitrary key-value metadata
                   */
                  metadata: {
                      [key: string]: unknown;
                  };
                  /**
                   * Page Content
                   * @description Document text
                   */
                  pageContent: string;
              }[];
              /**
               * State
               * @description Additional agent state information
               */
              state: {
                  [key: string]: unknown;
              };
              /**
               * Used Tools
               * @description Tools used by the agent during reasoning
               */
              usedTools: {
                  /**
                   * Tool
                   * @description Name of the tool used
                   */
                  tool: string;
                  /**
                   * Tool Input
                   * @description Input parameters passed to the tool
                   */
                  toolInput: {
                      [key: string]: unknown;
                  };
                  /**
                   * Tool Output
                   * @description Output returned by the tool
                   */
                  toolOutput: string;
              }[];
          }[];
          /**
           * Chat Id
           * @description Chat ID within the chatflow
           */
          chatId: string;
          /**
           * Chat Type
           * @description Type of chat: INTERNAL or EXTERNAL
           * @enum {string}
           */
          chatType: "INTERNAL" | "EXTERNAL";
          /**
           * Chatflowid
           * @description Chatflow ID this message belongs to
           */
          chatflowid: string;
          /**
           * Content
           * @description Message content
           */
          content: string;
          /**
           * Created Date
           * Format: date-time
           * @description ISO 8601 timestamp when the message was created
           */
          createdDate: unknown;
          /**
           * File Annotations
           * @description Annotations on files associated with the message
           */
          fileAnnotations: {
              /**
               * File Name
               * @description Name of the annotated file
               */
              fileName: string;
              /**
               * File Path
               * @description Path to the file annotation
               */
              filePath: string;
          }[];
          /**
           * File Uploads
           * @description Files uploaded as part of the message
           */
          fileUploads: {
              /**
               * Data
               * @description Base64-encoded file data
               */
              data: string;
              /**
               * Mime
               * @description MIME type of the uploaded file
               */
              mime: string;
              /**
               * Name
               * @description Original filename of the upload
               */
              name: string;
              /**
               * Type
               * @description Type of the file upload
               */
              type: string;
          }[];
          /**
           * Id
           * @description Message ID
           */
          id: string;
          /**
           * Lead Email
           * @description Lead email if available for the message
           * @default null
           */
          leadEmail: string | null;
          /**
           * Memory Type
           * @description Memory type associated with the message
           */
          memoryType: string;
          /**
           * Role
           * @description Role of the message origin, e.g., apiMessage
           */
          role: string;
          /**
           * Session Id
           * @description Session ID of the message session
           */
          sessionId: string;
          /**
           * Source Documents
           * @description Documents referenced in the message
           */
          sourceDocuments: {
              /**
               * Metadata
               * @description Arbitrary key-value metadata
               */
              metadata: {
                  [key: string]: unknown;
              };
              /**
               * Page Content
               * @description Document text
               */
              pageContent: string;
          }[];
          /**
           * Used Tools
           * @description Tools used for the message
           */
          usedTools: {
              /**
               * Tool
               * @description Name of the tool used
               */
              tool: string;
              /**
               * Tool Input
               * @description Input parameters passed to the tool
               */
              toolInput: {
                  [key: string]: unknown;
              };
              /**
               * Tool Output
               * @description Output returned by the tool
               */
              toolOutput: string;
          }[];
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_UPDATE_CHATFLOW_DETAILS tool input.
 */
type FLOWISEAI_UPDATE_CHATFLOW_DETAILS_INPUT = {
  /**
   * Analytic
   * @description JSON string for analytics settings
   * @default null
   */
  analytic: string | null;
  /**
   * Api Config
   * @description JSON string for API connection/configuration details
   * @default null
   */
  apiConfig: string | null;
  /**
   * Apikeyid
   * @description Identifier of the API key associated with the chatflow
   * @default null
   */
  apikeyid: string | null;
  /**
   * Category
   * @description Semicolon-delimited categories for grouping
   * @default null
   */
  category: string | null;
  /**
   * Chatbot Config
   * @description JSON string for chatbot-specific configuration
   * @default null
   */
  chatbotConfig: string | null;
  /**
   * Created Date
   * @description ISO-8601 timestamp of creation (server-managed)
   * @default null
   */
  createdDate: string | null;
  /**
   * Deployed
   * @description Deployment status of the chatflow
   * @default null
   */
  deployed: boolean | null;
  /**
   * Flow Data
   * @description JSON string representing the flow graph/configuration
   * @default null
   */
  flowData: string | null;
  /**
   * Id
   * @description Unique identifier of the chatflow to update
   */
  id?: string;
  /**
   * Is Public
   * @description Whether the chatflow is publicly accessible
   * @default null
   */
  isPublic: boolean | null;
  /**
   * Name
   * @description New name for the chatflow
   * @default null
   */
  name: string | null;
  /**
   * Speech To Text
   * @description JSON string for speech-to-text configuration
   * @default null
   */
  speechToText: string | null;
  /**
   * Type
   * @description Type of the chatflow
   * @default null
   * @enum {string|null}
   */
  type: "CHATFLOW" | "MULTIAGENT" | null;
  /**
   * Updated Date
   * @description ISO-8601 timestamp of last update (server-managed)
   * @default null
   */
  updatedDate: string | null;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_UPDATE_CHATFLOW_DETAILS tool output.
 */
type FLOWISEAI_UPDATE_CHATFLOW_DETAILS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Analytic
       * @description Analytics settings JSON string
       * @default null
       */
      analytic: string | null;
      /**
       * Api Config
       * @description API configuration JSON string
       * @default null
       */
      apiConfig: string | null;
      /**
       * Apikeyid
       * @description API key ID associated with the chatflow
       * @default null
       */
      apikeyid: string | null;
      /**
       * Category
       * @description Semicolon-delimited categories
       * @default null
       */
      category: string | null;
      /**
       * Chatbot Config
       * @description Chatbot configuration JSON string
       * @default null
       */
      chatbotConfig: string | null;
      /**
       * Created Date
       * @description ISO-8601 timestamp when created
       */
      createdDate: string;
      /**
       * Deployed
       * @description Deployment status of the chatflow
       */
      deployed: boolean;
      /**
       * Flow Data
       * @description Flow graph/configuration as JSON string
       */
      flowData: string;
      /**
       * Id
       * @description Unique identifier of the chatflow
       */
      id: string;
      /**
       * Is Public
       * @description Whether the chatflow is publicly accessible
       */
      isPublic: boolean;
      /**
       * Name
       * @description Name of the chatflow
       */
      name: string;
      /**
       * Speech To Text
       * @description Speech-to-text configuration JSON string
       * @default null
       */
      speechToText: string | null;
      /**
       * Type
       * @description Type of the chatflow
       * @enum {string}
       */
      type: "CHATFLOW" | "MULTIAGENT";
      /**
       * Updated Date
       * @description ISO-8601 timestamp when last updated
       */
      updatedDate: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_UPDATE_TOOL_BY_ID tool input.
 */
type FLOWISEAI_UPDATE_TOOL_BY_ID_INPUT = {
  /**
   * Color
   * @description Hexadecimal color code for the tool
   * @default null
   */
  color: string | null;
  /**
   * Created Date
   * @description ISO 8601 timestamp when the tool was created
   * @default null
   */
  createdDate: string | null;
  /**
   * Description
   * @description Description of the tool
   * @default null
   */
  description: string | null;
  /**
   * Func
   * @description Functionality description or code for the tool, if any
   * @default null
   */
  func: string | null;
  /**
   * Icon Src
   * @description URL for the tool's icon, if available
   * @default null
   */
  iconSrc: string | null;
  /**
   * Id
   * @description Unique identifier of the tool to update
   */
  id?: string;
  /**
   * Name
   * @description Name of the tool
   * @default null
   */
  name: string | null;
  /**
   * Schema
   * @description JSON schema associated with the tool, if any
   * @default null
   */
  schema: string | null;
  /**
   * Updated Date
   * @description ISO 8601 timestamp when the tool was last updated
   * @default null
   */
  updatedDate: string | null;
};

/**
 * Type of FLOWISEAI's FLOWISEAI_UPDATE_TOOL_BY_ID tool output.
 */
type FLOWISEAI_UPDATE_TOOL_BY_ID_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Color
       * @description Hexadecimal color code for the tool
       */
      color: string;
      /**
       * Created Date
       * @description ISO 8601 timestamp when the tool was created
       */
      createdDate: string;
      /**
       * Description
       * @description Description of the tool
       */
      description: string;
      /**
       * Func
       * @description Functionality description or code for the tool, if any
       * @default null
       */
      func: string | null;
      /**
       * Icon Src
       * @description URL of the tool's icon, if available
       * @default null
       */
      iconSrc: string | null;
      /**
       * Id
       * @description Unique identifier for the tool (UUID)
       */
      id: string;
      /**
       * Name
       * @description Name of the tool
       */
      name: string;
      /**
       * Schema
       * @description JSON schema associated with the tool, if any
       * @default null
       */
      schema: string | null;
      /**
       * Updated Date
       * @description ISO 8601 timestamp when the tool was last updated
       */
      updatedDate: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type map of all available tool input types for toolkit "FLOWISEAI".
 */
export type FLOWISEAI_TOOL_INPUTS = {
  CLONE_CHATFLOW: FLOWISEAI_CLONE_CHATFLOW_INPUT
  CREATE_CHATFLOW: FLOWISEAI_CREATE_CHATFLOW_INPUT
  DELETE_CHATFLOW: FLOWISEAI_DELETE_CHATFLOW_INPUT
  DELETE_CHAT_MESSAGES: FLOWISEAI_DELETE_CHAT_MESSAGES_INPUT
  DELETE_TOOL_BY_ID: FLOWISEAI_DELETE_TOOL_BY_ID_INPUT
  EXPORT_CHATFLOW: FLOWISEAI_EXPORT_CHATFLOW_INPUT
  GET_ALL_CHATFLOWS: FLOWISEAI_GET_ALL_CHATFLOWS_INPUT
  GET_SINGLE_CHATFLOW: FLOWISEAI_GET_SINGLE_CHATFLOW_INPUT
  GET_TOOL_BY_ID: FLOWISEAI_GET_TOOL_BY_ID_INPUT
  IMPORT_CHATFLOW: FLOWISEAI_IMPORT_CHATFLOW_INPUT
  LIST_ALL_TOOLS: FLOWISEAI_LIST_ALL_TOOLS_INPUT
  LIST_CHAT_MESSAGES: FLOWISEAI_LIST_CHAT_MESSAGES_INPUT
  UPDATE_CHATFLOW_DETAILS: FLOWISEAI_UPDATE_CHATFLOW_DETAILS_INPUT
  UPDATE_TOOL_BY_ID: FLOWISEAI_UPDATE_TOOL_BY_ID_INPUT
}

/**
 * Type map of all available tool input types for toolkit "FLOWISEAI".
 */
export type FLOWISEAI_TOOL_OUTPUTS = {
  CLONE_CHATFLOW: FLOWISEAI_CLONE_CHATFLOW_OUTPUT
  CREATE_CHATFLOW: FLOWISEAI_CREATE_CHATFLOW_OUTPUT
  DELETE_CHATFLOW: FLOWISEAI_DELETE_CHATFLOW_OUTPUT
  DELETE_CHAT_MESSAGES: FLOWISEAI_DELETE_CHAT_MESSAGES_OUTPUT
  DELETE_TOOL_BY_ID: FLOWISEAI_DELETE_TOOL_BY_ID_OUTPUT
  EXPORT_CHATFLOW: FLOWISEAI_EXPORT_CHATFLOW_OUTPUT
  GET_ALL_CHATFLOWS: FLOWISEAI_GET_ALL_CHATFLOWS_OUTPUT
  GET_SINGLE_CHATFLOW: FLOWISEAI_GET_SINGLE_CHATFLOW_OUTPUT
  GET_TOOL_BY_ID: FLOWISEAI_GET_TOOL_BY_ID_OUTPUT
  IMPORT_CHATFLOW: FLOWISEAI_IMPORT_CHATFLOW_OUTPUT
  LIST_ALL_TOOLS: FLOWISEAI_LIST_ALL_TOOLS_OUTPUT
  LIST_CHAT_MESSAGES: FLOWISEAI_LIST_CHAT_MESSAGES_OUTPUT
  UPDATE_CHATFLOW_DETAILS: FLOWISEAI_UPDATE_CHATFLOW_DETAILS_OUTPUT
  UPDATE_TOOL_BY_ID: FLOWISEAI_UPDATE_TOOL_BY_ID_OUTPUT
}

// ------------------- //
//    Trigger types    //
// ------------------- //



/**
 * Map of Composio's FLOWISEAI toolkit.
 */
export const FLOWISEAI = {
  slug: "flowiseai",
  tools: {
    /**
     * Tool to clone an existing chatflow. Use when you need to duplicate a chatflow by its ID.
     */
    CLONE_CHATFLOW: "FLOWISEAI_CLONE_CHATFLOW",
    /**
     * Tool to create a new chatflow in FlowiseAI. Use when you need to programmatically set up chatflows with custom configuration. Call after preparing the chatflow parameters.
     */
    CREATE_CHATFLOW: "FLOWISEAI_CREATE_CHATFLOW",
    /**
     * Tool to delete a chatflow by its ID. Use after confirming the chatflow ID is correct.
     */
    DELETE_CHATFLOW: "FLOWISEAI_DELETE_CHATFLOW",
    /**
     * Tool to delete chat messages for a specific chatflow. Use when you need to remove messages based on optional filters. Use after confirming the chatflow ID.
     */
    DELETE_CHAT_MESSAGES: "FLOWISEAI_DELETE_CHAT_MESSAGES",
    /**
     * Tool to delete a specific FlowiseAI tool by ID. Use after confirming the tool ID is correct.
     */
    DELETE_TOOL_BY_ID: "FLOWISEAI_DELETE_TOOL_BY_ID",
    /**
     * Tool to export a chatflow by its ID. Use after confirming the chatflow exists.
     */
    EXPORT_CHATFLOW: "FLOWISEAI_EXPORT_CHATFLOW",
    /**
     * Tool to retrieve all chatflows. Use when you need to list existing chatflows after authentication.
     */
    GET_ALL_CHATFLOWS: "FLOWISEAI_GET_ALL_CHATFLOWS",
    /**
     * Tool to retrieve a chatflow by its ID. Use when you have a chatflow ID and need its full details.
     */
    GET_SINGLE_CHATFLOW: "FLOWISEAI_GET_SINGLE_CHATFLOW",
    /**
     * Tool to retrieve a specific FlowiseAI tool by its ID. Use when you need detailed metadata of a tool before interacting with it.
     */
    GET_TOOL_BY_ID: "FLOWISEAI_GET_TOOL_BY_ID",
    /**
     * Tool to import a chatflow from an exported JSON file. Use after obtaining the exported chatflow data.
     */
    IMPORT_CHATFLOW: "FLOWISEAI_IMPORT_CHATFLOW",
    /**
     * Tool to retrieve a list of all tools. Use when you need to list every tool available after authentication.
     */
    LIST_ALL_TOOLS: "FLOWISEAI_LIST_ALL_TOOLS",
    /**
     * Tool to list chat messages of a chatflow. Use after selecting a chatflow when you need to view its messages.
     */
    LIST_CHAT_MESSAGES: "FLOWISEAI_LIST_CHAT_MESSAGES",
    /**
     * Tool to update details of an existing chatflow. Use when you have confirmed the chatflow ID and want to modify its fields.
     */
    UPDATE_CHATFLOW_DETAILS: "FLOWISEAI_UPDATE_CHATFLOW_DETAILS",
    /**
     * Tool to update a specific tool by its ID. Use when you need to modify existing tool metadata after retrieval. Call after confirming the fields you want to change.
     */
    UPDATE_TOOL_BY_ID: "FLOWISEAI_UPDATE_TOOL_BY_ID",
  },
  triggerTypes: {},
}

/**
 * Type map of all available trigger payloads for toolkit "FLOWISEAI".
 */
export type FLOWISEAI_TRIGGER_PAYLOADS = {}

/**
 * Type map of all available trigger events for toolkit "FLOWISEAI".
 */
export type FLOWISEAI_TRIGGER_EVENTS = {}
