// --------------- //
//    Tool types   //
// --------------- //



/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_GET_ITEM tool input.
 */
type ZOHO_INVOICE_GET_ITEM_INPUT = {
  /**
   * Item Id
   * @description Unique ID of the item to retrieve
   */
  item_id?: string;
  /**
   * Organization Id
   * @description The Zoho Invoice organization ID (X-com-zoho-invoice-organizationid header)
   */
  organization_id?: string;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_GET_ITEM tool output.
 */
type ZOHO_INVOICE_GET_ITEM_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Code
       * @description 0 indicates success
       */
      code: number;
      /**
       * Item
       * @description The retrieved item details
       */
      item: {
          /**
           * Custom Fields
           * @description List of custom fields
           * @default null
           */
          custom_fields: {
              /**
               * Customfield Id
               * @description Custom field ID
               */
              customfield_id: string;
              /**
               * Value
               * @description Value of the custom field
               */
              value: string;
          }[] | null;
          /**
           * Description
           * @description Description for the item
           * @default null
           */
          description: string | null;
          /**
           * Hsn Or Sac
           * @description HSN or SAC code
           * @default null
           */
          hsn_or_sac: string | null;
          /**
           * Item Id
           * @description Unique ID generated by the server for an item
           */
          item_id: string;
          /**
           * Item Tax Preferences
           * @description List of tax preferences
           * @default null
           */
          item_tax_preferences: {
              /**
               * Tax Id
               * @description ID of the tax to be associated to the item
               */
              tax_id: string;
              /**
               * Tax Specification
               * @description Tax specification (e.g., intra or interstate)
               */
              tax_specification: string;
          }[] | null;
          /**
           * Name
           * @description Name of the item
           */
          name: string;
          /**
           * Product Type
           * @description Type of an item (goods or service)
           * @default null
           */
          product_type: string | null;
          /**
           * Rate
           * @description Per unit price of an item
           */
          rate: number;
          /**
           * Sat Item Key Code
           * @description SAT item key code
           * @default null
           */
          sat_item_key_code: string | null;
          /**
           * Sku
           * @description SKU or Stock Keeping Unit
           * @default null
           */
          sku: string | null;
          /**
           * Status
           * @description Status of the item (active or inactive)
           */
          status: string;
          /**
           * Tax Id
           * @description ID of the tax to be associated
           * @default null
           */
          tax_id: string | null;
          /**
           * Tax Name
           * @description Name of the tax included
           * @default null
           */
          tax_name: string | null;
          /**
           * Tax Percentage
           * @description Percent of the tax
           * @default null
           */
          tax_percentage: string | null;
          /**
           * Tax Type
           * @description Type of the tax
           * @default null
           */
          tax_type: string | null;
          /**
           * Unitkey Code
           * @description Unit key code
           * @default null
           */
          unitkey_code: string | null;
      };
      /**
       * Message
       * @description Response message from API
       */
      message: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_CONTACTS tool input.
 */
type ZOHO_INVOICE_LIST_CONTACTS_INPUT = {
  /**
   * Address
   * @description Search contacts by any of the address fields (exact match)
   * @default null
   */
  address: string | null;
  /**
   * Address Contains
   * @description Search contacts by any of the address fields (substring match)
   * @default null
   */
  address_contains: string | null;
  /**
   * Address Startswith
   * @description Search contacts by any of the address fields (prefix match)
   * @default null
   */
  address_startswith: string | null;
  /**
   * Company Name
   * @description Search contacts by company name (exact match)
   * @default null
   */
  company_name: string | null;
  /**
   * Company Name Contains
   * @description Search contacts by company name (substring match)
   * @default null
   */
  company_name_contains: string | null;
  /**
   * Company Name Startswith
   * @description Search contacts by company name (prefix match)
   * @default null
   */
  company_name_startswith: string | null;
  /**
   * Contact Name
   * @description Search contacts by contact name (exact match)
   * @default null
   */
  contact_name: string | null;
  /**
   * Contact Name Contains
   * @description Search contacts by contact name (substring match)
   * @default null
   */
  contact_name_contains: string | null;
  /**
   * Contact Name Startswith
   * @description Search contacts by contact name (prefix match)
   * @default null
   */
  contact_name_startswith: string | null;
  /**
   * Email
   * @description Search contacts by email ID of the contact person (exact match)
   * @default null
   */
  email: string | null;
  /**
   * Email Contains
   * @description Search contacts by email ID of the contact person (substring match)
   * @default null
   */
  email_contains: string | null;
  /**
   * Email Startswith
   * @description Search contacts by email ID of the contact person (prefix match)
   * @default null
   */
  email_startswith: string | null;
  /**
   * Filter By
   * @description Filter contacts by status
   * @default null
   * @enum {string|null}
   */
  filter_by: "Status.All" | "Status.Active" | "Status.Inactive" | "Status.Duplicate" | "Status.Crm" | null;
  /**
   * First Name
   * @description Search contacts by first name (exact match)
   * @default null
   */
  first_name: string | null;
  /**
   * First Name Contains
   * @description Search contacts by first name (substring match)
   * @default null
   */
  first_name_contains: string | null;
  /**
   * First Name Startswith
   * @description Search contacts by first name (prefix match)
   * @default null
   */
  first_name_startswith: string | null;
  /**
   * Last Name
   * @description Search contacts by last name (exact match)
   * @default null
   */
  last_name: string | null;
  /**
   * Last Name Contains
   * @description Search contacts by last name (substring match)
   * @default null
   */
  last_name_contains: string | null;
  /**
   * Last Name Startswith
   * @description Search contacts by last name (prefix match)
   * @default null
   */
  last_name_startswith: string | null;
  /**
   * Organization Id
   * @description The Zoho organization ID. Must be passed as query parameter 'organization_id'.
   */
  organization_id?: string;
  /**
   * Page
   * @description Page number for pagination, starts at 1
   * @default null
   */
  page: number | null;
  /**
   * Per Page
   * @description Number of contacts per page, max 200
   * @default null
   */
  per_page: number | null;
  /**
   * Phone
   * @description Search contacts by phone number of the contact person (exact match)
   * @default null
   */
  phone: string | null;
  /**
   * Phone Contains
   * @description Search contacts by phone number of the contact person (substring match)
   * @default null
   */
  phone_contains: string | null;
  /**
   * Phone Startswith
   * @description Search contacts by phone number of the contact person (prefix match)
   * @default null
   */
  phone_startswith: string | null;
  /**
   * Search Text
   * @description Search contacts by contact name or notes
   * @default null
   */
  search_text: string | null;
  /**
   * Sort Column
   * @description Sort contacts by the specified column
   * @default null
   * @enum {string|null}
   */
  sort_column: "contact_name" | "first_name" | "last_name" | "email" | "outstanding_receivable_amount" | "created_time" | "last_modified_time" | null;
  /**
   * Zcrm Account Id
   * @description CRM Account ID for the contact
   * @default null
   */
  zcrm_account_id: string | null;
  /**
   * Zcrm Contact Id
   * @description CRM Contact ID for the contact
   * @default null
   */
  zcrm_contact_id: string | null;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_CONTACTS tool output.
 */
type ZOHO_INVOICE_LIST_CONTACTS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Code
       * @description Response code
       */
      code: number;
      /**
       * Contacts
       * @description List of contacts
       */
      contacts: {
          /**
           * Company Name
           * @description Company name of the contact
           */
          company_name: string;
          /**
           * Contact Id
           * @description Unique identifier for the contact
           */
          contact_id: number;
          /**
           * Contact Name
           * @description Name of the contact
           */
          contact_name: string;
          /**
           * Contact Type
           * @description Type of contact (e.g., customer)
           */
          contact_type: string;
          /**
           * Created Time
           * @description Contact creation time in ISO 8601 format
           */
          created_time: string;
          /**
           * Currency Code
           * @description Currency code associated with the contact
           */
          currency_code: string;
          /**
           * Currency Id
           * @description Currency ID associated with the contact
           */
          currency_id: number;
          /**
           * Email
           * @description Email address of the contact person
           */
          email: string;
          /**
           * First Name
           * @description First name of contact person
           * @default null
           */
          first_name: string | null;
          /**
           * Last Modified Time
           * @description Last modified time in ISO 8601 format
           */
          last_modified_time: string;
          /**
           * Last Name
           * @description Last name of contact person
           * @default null
           */
          last_name: string | null;
          /**
           * Mobile
           * @description Mobile number of the contact person
           * @default null
           */
          mobile: string | null;
          /**
           * Outstanding Receivable Amount
           * @description Outstanding receivable amount
           */
          outstanding_receivable_amount: number;
          /**
           * Payment Terms
           * @description Payment terms in days
           */
          payment_terms: number;
          /**
           * Payment Terms Label
           * @description Label for payment terms
           */
          payment_terms_label: string;
          /**
           * Phone
           * @description Phone number of the contact person
           */
          phone: string;
          /**
           * Unused Credits Receivable Amount
           * @description Unused credits receivable amount
           */
          unused_credits_receivable_amount: number;
      }[];
      /**
       * Message
       * @description Response message
       */
      message: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_EXPENSES tool input.
 */
type ZOHO_INVOICE_LIST_EXPENSES_INPUT = {
  /**
   * Page
   * @description Page number for pagination, starts at 1
   * @default null
   */
  page: number | null;
  /**
   * Per Page
   * @description Number of records per page; must be ≥ 1
   * @default null
   */
  per_page: number | null;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_EXPENSES tool output.
 */
type ZOHO_INVOICE_LIST_EXPENSES_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Code
       * @description API response code; 0 indicates success
       */
      code: number;
      /**
       * Expenses
       * @description List of expense summaries
       */
      expenses: {
          /**
           * Currency Code
           * @description Currency code, e.g. USD
           */
          currency_code: string;
          /**
           * Date
           * @description Expense date (YYYY-MM-DD)
           */
          date: string;
          /**
           * Expense Id
           * @description Unique ID of the expense
           */
          expense_id: number;
          /**
           * Status
           * @description Expense status
           */
          status: string;
          /**
           * Total
           * @description Total expense amount
           */
          total: number;
      }[];
      /**
       * Message
       * @description API response message
       */
      message: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_INVOICES tool input.
 */
type ZOHO_INVOICE_LIST_INVOICES_INPUT = {
  /**
   * Balance
   * @description Unpaid balance of the invoice
   * @default null
   */
  balance: number | null;
  /**
   * Custom Field
   * @description Search by custom field (exact match)
   * @default null
   */
  custom_field: string | null;
  /**
   * Custom Field Contains
   * @description Search by custom field (substring match)
   * @default null
   */
  custom_field_contains: string | null;
  /**
   * Custom Field Startswith
   * @description Search by custom field (prefix match)
   * @default null
   */
  custom_field_startswith: string | null;
  /**
   * Customer Id
   * @description ID of the customer
   * @default null
   */
  customer_id: string | null;
  /**
   * Customer Name
   * @description Search by customer name (exact match)
   * @default null
   */
  customer_name: string | null;
  /**
   * Date
   * @description Invoice date (yyyy-mm-dd)
   * @default null
   */
  date: string | null;
  /**
   * Date After
   * @description Fetch invoices after this date
   * @default null
   */
  date_after: string | null;
  /**
   * Date Before
   * @description Fetch invoices before this date
   * @default null
   */
  date_before: string | null;
  /**
   * Date End
   * @description End date for invoice date range
   * @default null
   */
  date_end: string | null;
  /**
   * Date Start
   * @description Start date for invoice date range
   * @default null
   */
  date_start: string | null;
  /**
   * Due Date
   * @description Due date of the invoice (yyyy-mm-dd)
   * @default null
   */
  due_date: string | null;
  /**
   * Due Date After
   * @description Fetch invoices due after this date
   * @default null
   */
  due_date_after: string | null;
  /**
   * Due Date Before
   * @description Fetch invoices due before this date
   * @default null
   */
  due_date_before: string | null;
  /**
   * Due Date End
   * @description End date for due date range
   * @default null
   */
  due_date_end: string | null;
  /**
   * Due Date Start
   * @description Start date for due date range
   * @default null
   */
  due_date_start: string | null;
  /**
   * Email
   * Format: email
   * @description Search by email ID of the contact person
   */
  email?: unknown;
  /**
   * Filter By
   * @description Filter invoices by status or payment expected date
   * @default null
   * @enum {string|null}
   */
  filter_by: "Status.All" | "Status.Sent" | "Status.Draft" | "Status.OverDue" | "Status.Paid" | "Status.Void" | "Status.Unpaid" | "Status.PartiallyPaid" | "Status.Viewed" | "Date.PaymentExpectedDate" | null;
  /**
   * Invoice Number
   * @description Unique number assigned to the invoice (exact match)
   * @default null
   */
  invoice_number: string | null;
  /**
   * Item Description
   * @description Search by item description (exact match)
   * @default null
   */
  item_description: string | null;
  /**
   * Item Description Contains
   * @description Search by item description (substring match)
   * @default null
   */
  item_description_contains: string | null;
  /**
   * Item Description Startswith
   * @description Search by item description (prefix match)
   * @default null
   */
  item_description_startswith: string | null;
  /**
   * Item Id
   * @description Unique identifier for the item
   * @default null
   */
  item_id: string | null;
  /**
   * Item Name
   * @description Search by item name (exact match)
   * @default null
   */
  item_name: string | null;
  /**
   * Item Name Contains
   * @description Search by item name (substring match)
   * @default null
   */
  item_name_contains: string | null;
  /**
   * Item Name Startswith
   * @description Search by item name (prefix match)
   * @default null
   */
  item_name_startswith: string | null;
  /**
   * Page
   * @description Page number for pagination, starts at 1
   * @default null
   */
  page: number | null;
  /**
   * Per Page
   * @description Number of items per page for pagination
   * @default null
   */
  per_page: number | null;
  /**
   * Recurring Invoice Id
   * @description ID of the recurring invoice
   * @default null
   */
  recurring_invoice_id: string | null;
  /**
   * Reference Number
   * @description Reference number of the invoice
   * @default null
   */
  reference_number: string | null;
  /**
   * Search Text
   * @description Search by invoice number, purchase order, or customer name
   * @default null
   */
  search_text: string | null;
  /**
   * Sort Column
   * @description Sort invoices by specified column
   * @default null
   * @enum {string|null}
   */
  sort_column: "customer_name" | "invoice_number" | "date" | "due_date" | "total" | "balance" | "created_time" | null;
  /**
   * Status
   * @description Status of the invoice
   * @default null
   * @enum {string|null}
   */
  status: "sent" | "draft" | "overdue" | "paid" | "void" | "unpaid" | "partially_paid" | "viewed" | null;
  /**
   * Total
   * @description Total amount of the invoice
   * @default null
   */
  total: number | null;
  /**
   * Zcrm Potential Id
   * @description CRM Deal potential ID
   * @default null
   */
  zcrm_potential_id: string | null;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_INVOICES tool output.
 */
type ZOHO_INVOICE_LIST_INVOICES_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Code
       * @description Response code of the API call
       */
      code: number;
      /**
       * Invoices
       * @description List of invoices
       */
      invoices: {
          /**
           * Ach Payment Initiated
           * @description Indicates if ACH payment was initiated
           */
          ach_payment_initiated: boolean;
          /**
           * Adjustment
           * @description Adjustment amount applied to the invoice
           */
          adjustment: number;
          /**
           * Balance
           * @description Unpaid balance of the invoice
           */
          balance: number;
          /**
           * Client Viewed Time
           * @description Time when the client viewed the invoice
           */
          client_viewed_time: string;
          /**
           * Created Time
           * @description Time when the invoice was created
           */
          created_time: string;
          /**
           * Currency Code
           * @description Currency code (e.g., USD)
           */
          currency_code: string;
          /**
           * Currency Id
           * @description Unique identifier for the currency
           */
          currency_id: string;
          /**
           * Custom Fields
           * @description List of custom fields
           */
          custom_fields: {
              /**
               * Label
               * @description Label of the custom field
               */
              label: string;
              /**
               * Value
               * @description Value of the custom field
               */
              value: string;
          }[];
          /**
           * Customer Id
           * @description Unique identifier for the customer
           */
          customer_id: string;
          /**
           * Customer Name
           * @description Name of the customer
           */
          customer_name: string;
          /**
           * Date
           * @description Invoice date in yyyy-mm-dd format
           */
          date: string;
          /**
           * Documents
           * @description Documents associated with the invoice
           */
          documents: string;
          /**
           * Due Date
           * @description Due date of the invoice in yyyy-mm-dd format
           */
          due_date: string;
          /**
           * Due Days
           * @description Number of days until due date
           */
          due_days: string;
          /**
           * Exchange Rate
           * @description Exchange rate applied to the invoice
           */
          exchange_rate: number;
          /**
           * Has Attachment
           * @description Indicates if the invoice has attachments
           */
          has_attachment: boolean;
          /**
           * Invoice Id
           * @description Unique identifier for the invoice
           */
          invoice_id: string;
          /**
           * Invoice Number
           * @description Invoice number
           */
          invoice_number: string;
          /**
           * Is Emailed
           * @description Indicates if the invoice was emailed
           */
          is_emailed: boolean;
          /**
           * Is Viewed By Client
           * @description Indicates if viewed by the client
           */
          is_viewed_by_client: boolean;
          /**
           * Last Modified Time
           * @description Time when the invoice was last modified
           */
          last_modified_time: string;
          /**
           * Last Payment Date
           * @description Date when the last payment was made
           */
          last_payment_date: string;
          /**
           * Last Reminder Sent Date
           * @description Date when the last reminder was sent
           */
          last_reminder_sent_date: string;
          /**
           * Payment Expected Date
           * @description Expected date of payment
           */
          payment_expected_date: string;
          /**
           * Reference Number
           * @description Reference number of the invoice
           */
          reference_number: string;
          /**
           * Reminders Sent
           * @description Number of reminders sent for the invoice
           */
          reminders_sent: number;
          /**
           * Salesperson Id
           * @description Unique identifier for the salesperson
           */
          salesperson_id: string;
          /**
           * Salesperson Name
           * @description Name of the salesperson
           */
          salesperson_name: string;
          /**
           * Schedule Time
           * @description Scheduled time for the invoice
           */
          schedule_time: string;
          /**
           * Shipping Charge
           * @description Shipping charge applied to the invoice
           */
          shipping_charge: number;
          /**
           * Status
           * @description Status of the invoice
           */
          status: string;
          /**
           * Total
           * @description Total amount of the invoice
           */
          total: number;
          /**
           * Write Off Amount
           * @description Amount written off for the invoice
           */
          write_off_amount: number;
      }[];
      /**
       * Message
       * @description Response message
       */
      message: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_ITEMS tool input.
 */
type ZOHO_INVOICE_LIST_ITEMS_INPUT = {
  /**
   * Filter By
   * @description Filter items by status or type (e.g., 'active')
   * @default null
   */
  filter_by: string | null;
  /**
   * Organization Id
   * @description The Zoho Invoice organization ID. Must be passed as query parameter 'organization_id'.
   */
  organization_id?: string;
  /**
   * Page
   * @description Page number for pagination, starts at 1
   * @default null
   */
  page: number | null;
  /**
   * Per Page
   * @description Number of items per page, must be ≥ 1
   * @default null
   */
  per_page: number | null;
  /**
   * Search Text
   * @description Free-text search to filter items by name or description
   * @default null
   */
  search_text: string | null;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_ITEMS tool output.
 */
type ZOHO_INVOICE_LIST_ITEMS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Code
       * @description API response code, 0 indicates success
       */
      code: number;
      /**
       * Items
       * @description List of item records
       */
      items: {
          /**
           * Custom Fields
           * @description List of custom fields for the item
           * @default null
           */
          custom_fields: {
              /**
               * Customfield Id
               * @description Custom field ID
               */
              customfield_id: string;
              /**
               * Value
               * @description Value of the custom field
               */
              value: string;
          }[] | null;
          /**
           * Description
           * @description Description for the item
           * @default null
           */
          description: string | null;
          /**
           * Hsn Or Sac
           * @description HSN or SAC code
           * @default null
           */
          hsn_or_sac: string | null;
          /**
           * Item Id
           * @description Unique ID generated by the server for an item
           */
          item_id: string;
          /**
           * Item Tax Preferences
           * @description List of tax preferences for the item
           * @default null
           */
          item_tax_preferences: {
              /**
               * Tax Id
               * @description ID of the tax associated with the item
               */
              tax_id: string;
              /**
               * Tax Specification
               * @description Tax specification (e.g., intra or interstate)
               */
              tax_specification: string;
          }[] | null;
          /**
           * Name
           * @description Name of the item
           */
          name: string;
          /**
           * Product Type
           * @description Type of an item (goods or service)
           * @default null
           */
          product_type: string | null;
          /**
           * Rate
           * @description Per unit price of an item
           */
          rate: number;
          /**
           * Sat Item Key Code
           * @description SAT item key code
           * @default null
           */
          sat_item_key_code: string | null;
          /**
           * Sku
           * @description SKU or Stock Keeping Unit
           * @default null
           */
          sku: string | null;
          /**
           * Status
           * @description Status of the item (active or inactive)
           */
          status: string;
          /**
           * Tax Id
           * @description ID of the tax associated with the item
           * @default null
           */
          tax_id: string | null;
          /**
           * Tax Name
           * @description Name of the tax included
           * @default null
           */
          tax_name: string | null;
          /**
           * Tax Percentage
           * @description Percent of the tax
           * @default null
           */
          tax_percentage: string | null;
          /**
           * Tax Type
           * @description Type of the tax
           * @default null
           */
          tax_type: string | null;
          /**
           * Unit
           * @description Measurement unit
           * @default null
           */
          unit: string | null;
          /**
           * Unitkey Code
           * @description Unit key code
           * @default null
           */
          unitkey_code: string | null;
      }[];
      /**
       * Message
       * @description API response message
       */
      message: string;
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_PAYMENTS tool input.
 */
type ZOHO_INVOICE_LIST_PAYMENTS_INPUT = {
  /**
   * Customer Id
   * @description Filter payments for a specific customer by ID
   * @default null
   */
  customer_id: string | null;
  /**
   * Date End
   * @description Filter payments made on or before this date (YYYY-MM-DD)
   * @default null
   */
  date_end: string | null;
  /**
   * Date Start
   * @description Filter payments made on or after this date (YYYY-MM-DD)
   * @default null
   */
  date_start: string | null;
  /**
   * Filter By
   * @description Filter payments by status
   * @default null
   * @enum {string|null}
   */
  filter_by: "Status.All" | "Status.Success" | "Status.Refunded" | "Status.Void" | null;
  /**
   * Invoice Id
   * @description Filter payments for a specific invoice by ID
   * @default null
   */
  invoice_id: string | null;
  /**
   * Mode
   * @description Filter by payment mode (e.g., 'Cash', 'Credit Card')
   * @default null
   */
  mode: string | null;
  /**
   * Page
   * @description Page number for pagination, starts at 1
   * @default null
   */
  page: number | null;
  /**
   * Payment Number
   * @description Filter by payment number
   * @default null
   */
  payment_number: string | null;
  /**
   * Per Page
   * @description Number of payments per page, maximum 200
   * @default null
   */
  per_page: number | null;
  /**
   * Reference Number
   * @description Filter by reference number
   * @default null
   */
  reference_number: string | null;
  /**
   * Sort Column
   * @description Column to sort by
   * @default null
   * @enum {string|null}
   */
  sort_column: "payment_number" | "amount" | "date" | "mode" | "reference_number" | null;
  /**
   * Sort Order
   * @description Sort order: 'A' for ascending, 'D' for descending
   * @default null
   * @enum {string|null}
   */
  sort_order: "A" | "D" | null;
};

/**
 * Type of ZOHO_INVOICE's ZOHO_INVOICE_LIST_PAYMENTS tool output.
 */
type ZOHO_INVOICE_LIST_PAYMENTS_OUTPUT = {
  /**
   * Data
   * @description Data from the action execution
   */
  data?: {
      /**
       * Code
       * @description Response code of the API call
       */
      code: number;
      /**
       * Message
       * @description Response message
       */
      message: string;
      /**
       * Payments
       * @description List of payments
       */
      payments: {
          /**
           * Amount
           * @description Amount of the payment
           */
          amount: number;
          /**
           * Date
           * @description Payment date in YYYY-MM-DD format
           */
          date: string;
          /**
           * Description
           * @description Description for the payment
           * @default null
           */
          description: string | null;
          /**
           * Mode
           * @description Mode of payment
           */
          mode: string;
          /**
           * Payment Id
           * @description Unique identifier for the payment
           */
          payment_id: string;
          /**
           * Payment Number
           * @description Payment number
           */
          payment_number: string;
          /**
           * Reference Number
           * @description Reference number of the payment
           */
          reference_number: string;
      }[];
  };
  /**
   * Error
   * @description Error if any occurred during the execution of the action
   * @default null
   */
  error: string | null;
  /**
   * Successful
   * @description Whether or not the action execution was successful or not
   */
  successful?: boolean;
};

/**
 * Type map of all available tool input types for toolkit "ZOHO_INVOICE".
 */
export type ZOHO_INVOICE_TOOL_INPUTS = {
  GET_ITEM: ZOHO_INVOICE_GET_ITEM_INPUT
  LIST_CONTACTS: ZOHO_INVOICE_LIST_CONTACTS_INPUT
  LIST_EXPENSES: ZOHO_INVOICE_LIST_EXPENSES_INPUT
  LIST_INVOICES: ZOHO_INVOICE_LIST_INVOICES_INPUT
  LIST_ITEMS: ZOHO_INVOICE_LIST_ITEMS_INPUT
  LIST_PAYMENTS: ZOHO_INVOICE_LIST_PAYMENTS_INPUT
}

/**
 * Type map of all available tool input types for toolkit "ZOHO_INVOICE".
 */
export type ZOHO_INVOICE_TOOL_OUTPUTS = {
  GET_ITEM: ZOHO_INVOICE_GET_ITEM_OUTPUT
  LIST_CONTACTS: ZOHO_INVOICE_LIST_CONTACTS_OUTPUT
  LIST_EXPENSES: ZOHO_INVOICE_LIST_EXPENSES_OUTPUT
  LIST_INVOICES: ZOHO_INVOICE_LIST_INVOICES_OUTPUT
  LIST_ITEMS: ZOHO_INVOICE_LIST_ITEMS_OUTPUT
  LIST_PAYMENTS: ZOHO_INVOICE_LIST_PAYMENTS_OUTPUT
}

// ------------------- //
//    Trigger types    //
// ------------------- //



/**
 * Map of Composio's ZOHO_INVOICE toolkit.
 */
export const ZOHO_INVOICE = {
  slug: "zoho_invoice",
  tools: {
    /**
     * Tool to retrieve the details of a specific item by item id. use when you need to fetch an item's data after confirming its existence.
     */
    GET_ITEM: "ZOHO_INVOICE_GET_ITEM",
    /**
     * Tool to list contacts. use after obtaining the organization id to retrieve contacts with optional filters and pagination.
     */
    LIST_CONTACTS: "ZOHO_INVOICE_LIST_CONTACTS",
    /**
     * Tool to list all expenses with optional pagination. use when you need to retrieve expenses with simple pagination.
     */
    LIST_EXPENSES: "ZOHO_INVOICE_LIST_EXPENSES",
    /**
     * Tool to list invoices. use when you need to retrieve all invoices with optional filters and pagination.
     */
    LIST_INVOICES: "ZOHO_INVOICE_LIST_INVOICES",
    /**
     * Tool to list all items. use when you need to retrieve your item catalog with optional pagination and filtering after specifying the organization id.
     */
    LIST_ITEMS: "ZOHO_INVOICE_LIST_ITEMS",
    /**
     * Tool to list payments. use when you need to retrieve all payments with optional filters like customer, invoice, date range, and pagination.
     */
    LIST_PAYMENTS: "ZOHO_INVOICE_LIST_PAYMENTS",
  },
  triggerTypes: {},
}

/**
 * Type map of all available trigger payloads for toolkit "ZOHO_INVOICE".
 */
export type ZOHO_INVOICE_TRIGGER_PAYLOADS = {}

/**
 * Type map of all available trigger events for toolkit "ZOHO_INVOICE".
 */
export type ZOHO_INVOICE_TRIGGER_EVENTS = {}
